#!/bin/csh
#  aterm interpreter test
#  usage:
#    aitest lgi_file spc_file input_file output_file my_flag
#  !!! all files are without extensions !!!
#
echo "  aterm-int-test of "$1 ":" $2.spc "<-" $3.inp

set d=`date`
set tstfile = "/tmp/elan.test.$HOST.$d[4]"
/bin/rm -f $tstfile
set ELAN = $ELANLIB/../bin/`uname -m`/elan
$ELAN -b $5 --export $1.ref $1.lgi $2.spc 
$ELAN -b --import $1.ref < SAMPLES/$3.inp > $tstfile
diff SAMPLES/$4.out  $tstfile
/bin/rm -f $tstfile $1.ref
