#		(c)	INRIA-Lorraine & CRIN
#			615, rue du Jardin Botanique, BP 101
#		        54602 Villers-les-Nancy
#			France
#			email: elan@loria.fr
#
#	$Source: /users/protheo/pot/ELAN/CVSELAN/elan/sources/Compiler/RuntimeSupport/TermIO/Makefile.common,v $
#	$Revision: 1.1 $
#	$Date: 1999/11/12 15:14:19 $
#	$Author: moreau $

# import CC
# import FAST
# import ARCH
# import ARCHFLAG
# import SPECIAL_FLAG
# import ELANLIB

MAKEINSTALLDIRS =
MAKEDISTDIRS    = $(ELANDIST)/Compiler/RuntimeSupport/ACMatcher


SRC    = Makefile.common termIn.c termOut.c termIn.h termOut.h

all: 

makefile:

install:

dist: dist-dirs 
	cp $(SRC) $(ELANDIST)/Compiler/RuntimeSupport/TermIO

clean :
	rm -f core a.out main *.o *~ y.tab.[ch] y.output lex.yy.c $(ARCH)/*.o $(ARCH)/*.a

