//! Rust emission: the IR as a cargo crate (`Cargo.toml`, `src/main.rs`).
//!
//! Shape of the generated code (see `elan-runtime`, `tests/common/mod.rs`
//! of the runtime for the conventions):
//!
//! * per enum sort: `pub enum Nat { O, S(H<Nat>), ... }`, `impl_sort!`, a
//!   [`Print`](elan_runtime::Print) impl with the C printer's tokens;
//! * per builtin family that can be stuck: the enum of its stuck terms,
//!   with a `sort()` method (the ELAN sort of a stuck term, used to match
//!   injections);
//! * per operator: its normalisation function `pub fn name_code(a0: &T0,
//!   ...) -> T`, arguments in normal form, result in normal form; a defined
//!   operator's body is its decision tree followed by the stuck term (or
//!   `unreachable!` when the operator is total); each rule is a labelled
//!   block (`'r3: { ... }`) left by `break` when a pattern or a condition
//!   fails;
//! * `main`: the start term, normalised and printed by the runtime driver
//!   (strings printed raw, as the compiled C programs do).
//!
//! Variables and positions are references (`&T`); values are cloned only
//! when stored in a new term.

use std::fmt::Write as _;

use crate::ir::*;

/// The files of a generated crate.
pub struct Crate {
    pub cargo_toml: String,
    pub main_rs: String,
}

/// Generate the crate of `ir`: package and binary `bin_name`, depending on
/// the runtime crate at `runtime_path`.
pub fn emit_crate(ir: &Ir, bin_name: &str, runtime_path: &str) -> Crate {
    let cargo_toml = format!(
        "# Generated by elanc-rs from {prog}.ref: do not edit.\n\
         [package]\n\
         name = \"{bin}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         publish = false\n\
         \n\
         [[bin]]\n\
         name = \"{bin}\"\n\
         path = \"src/main.rs\"\n\
         \n\
         [dependencies]\n\
         elan-runtime = {{ path = {rt:?} }}\n\
         \n\
         [profile.release]\n\
         debug = false\n\
         \n\
         # a crate of its own, even inside another cargo workspace\n\
         [workspace]\n",
        prog = ir.program,
        bin = bin_name,
        rt = runtime_path,
    );
    Crate {
        cargo_toml,
        main_rs: Emitter::new(ir).main_rs(),
    }
}

/// Indented text.
struct Out {
    buf: String,
    indent: usize,
}

impl Out {
    fn line(&mut self, s: &str) {
        if s.is_empty() {
            self.buf.push('\n');
            return;
        }
        for _ in 0..self.indent {
            self.buf.push_str("    ");
        }
        self.buf.push_str(s);
        self.buf.push('\n');
    }
    fn open(&mut self, s: &str) {
        self.line(s);
        self.indent += 1;
    }
    fn close(&mut self, s: &str) {
        self.indent -= 1;
        self.line(s);
    }
    /// A comment, one `//` line per line of `s`.
    fn comment(&mut self, prefix: &str, s: &str) {
        for l in s.lines() {
            self.line(&format!("{prefix} {l}"));
        }
    }
}

/// Name of the Rust variable holding the term at a position.
fn occ_name(occ: &Occ) -> String {
    let mut s = format!("a{}", occ[0]);
    for i in &occ[1..] {
        let _ = write!(s, "_{i}");
    }
    s
}

struct Emitter<'a> {
    ir: &'a Ir,
    out: Out,
    /// counter of labels and fresh names in the current function
    fresh: usize,
}

impl<'a> Emitter<'a> {
    fn new(ir: &'a Ir) -> Self {
        Emitter {
            ir,
            out: Out {
                buf: String::new(),
                indent: 0,
            },
            fresh: 0,
        }
    }

    fn next(&mut self) -> usize {
        self.fresh += 1;
        self.fresh
    }

    // ------------------------------------------------------------------
    // Types and values
    // ------------------------------------------------------------------

    fn native(kind: BuiltinKind) -> &'static str {
        match kind {
            BuiltinKind::Int => "Int",
            BuiltinKind::Bool => "bool",
            BuiltinKind::Str => "Str",
        }
    }

    /// The Rust type of the terms of sort `s`.
    fn ty(&self, s: SortId) -> String {
        let sort = &self.ir.sorts[s];
        match &sort.repr {
            Repr::Enum { .. } => format!("H<{}>", sort.type_name),
            Repr::Family(f) => {
                let fam = &self.ir.families[*f];
                let v = Self::native(fam.kind);
                match &fam.stuck {
                    None => v.to_string(),
                    Some(e) => e.alias.clone(),
                }
            }
        }
    }

    /// Is sort `s` represented by `Builtin<V, S>`?
    fn wrapped(&self, s: SortId) -> bool {
        self.ir.family_of(s).map_or(false, |f| f.stuck.is_some())
    }

    /// A value of sort `s` from a native value expression.
    fn wrap(&self, s: SortId, v: &str) -> String {
        if self.wrapped(s) {
            format!("Builtin::Val({v})")
        } else {
            v.to_string()
        }
    }

    /// The type name of the enum holding the variant of operator `o`, and
    /// whether it is a family's stuck enum.
    fn variant_enum(&self, o: OpId) -> (String, bool) {
        let s = self.ir.ops[o].result;
        match &self.ir.sorts[s].repr {
            Repr::Enum { .. } => (self.ir.sorts[s].type_name.clone(), false),
            Repr::Family(f) => (
                self.ir.families[*f]
                    .stuck
                    .as_ref()
                    .expect("a variant in a family without stuck enum")
                    .type_name
                    .clone(),
                true,
            ),
        }
    }

    /// The term `o(a0, ..)` as stored (its variant), from argument
    /// references named `args`.
    fn build_variant(&self, o: OpId, args: &[String]) -> String {
        let op = &self.ir.ops[o];
        let (en, stuck) = self.variant_enum(o);
        let v = op.variant.as_ref().expect("operator without variant");
        let node = if args.is_empty() {
            format!("H::new({en}::{v})")
        } else {
            let a: Vec<String> = args.iter().map(|a| format!("{a}.clone()")).collect();
            format!("H::new({en}::{v}({}))", a.join(", "))
        };
        if stuck {
            format!("Builtin::Stuck({node})")
        } else {
            node
        }
    }

    /// An expression building the normal form of `e` (an owned value).
    fn expr(&self, e: &Expr, vars: &[VarIr]) -> String {
        match e {
            Expr::Var(v) => format!("{}.clone()", vars[*v].name),
            Expr::Int(n) => self.lit_int(*n),
            Expr::Str(s) => self.lit_str(s),
            Expr::Op { op, args } => {
                let o = &self.ir.ops[*op];
                match o.kind {
                    OpKind::Injection => self.expr(&args[0], vars),
                    OpKind::BoolConst(b) => self.wrap(o.result, if b { "true" } else { "false" }),
                    _ => {
                        let a: Vec<String> = args.iter().map(|a| self.arg(a, vars)).collect();
                        format!("{}({})", o.fun, a.join(", "))
                    }
                }
            }
        }
    }

    /// A reference to the normal form of `e`, as an argument.
    fn arg(&self, e: &Expr, vars: &[VarIr]) -> String {
        match e {
            Expr::Var(v) => vars[*v].name.clone(),
            Expr::Op { op, args } if matches!(self.ir.ops[*op].kind, OpKind::Injection) => {
                self.arg(&args[0], vars)
            }
            _ => format!("&{}", self.expr(e, vars)),
        }
    }

    fn int_sort(&self) -> Option<SortId> {
        self.ir
            .families
            .iter()
            .find(|f| f.kind == BuiltinKind::Int)
            .map(|f| f.base)
    }

    fn str_sort(&self) -> Option<SortId> {
        self.ir
            .families
            .iter()
            .find(|f| f.kind == BuiltinKind::Str)
            .map(|f| f.base)
    }

    fn lit_int(&self, n: i64) -> String {
        let v = if n < 0 {
            format!("({n})")
        } else {
            n.to_string()
        };
        self.wrap(self.int_sort().expect("builtinInt"), &v)
    }

    fn lit_str(&self, s: &str) -> String {
        self.wrap(
            self.str_sort().expect("builtinString"),
            &format!("Str::from({s:?})"),
        )
    }

    /// A test that the value at `scrut` (a reference) is the literal.
    fn lit_test(&self, s: SortId, scrut: &str, h: &Head) -> String {
        let test = |v: &str| -> String {
            match h {
                Head::Int(n) if *n < 0 => format!("*{v} == ({n})"),
                Head::Int(n) => format!("*{v} == {n}"),
                Head::Str(st) => format!("&**{v} == {st:?}"),
                Head::Op(o) => match self.ir.ops[*o].kind {
                    OpKind::BoolConst(true) => format!("*{v}"),
                    OpKind::BoolConst(false) => format!("!*{v}"),
                    _ => unreachable!("not a literal"),
                },
            }
        };
        if self.wrapped(s) {
            format!("matches!({scrut}, Builtin::Val(v) if {})", test("v"))
        } else {
            test(scrut)
        }
    }

    /// Test that a (wrapped) value at `scrut` is not a stuck term of
    /// another sort than `base` (the injection of `base` matches).
    fn inj_test(&self, base: SortId, scrut: &str) -> String {
        format!(
            "!matches!({scrut}, Builtin::Stuck(s) if s.sort() != {})",
            self.ir.sorts[base].index
        )
    }

    // ------------------------------------------------------------------
    // The file
    // ------------------------------------------------------------------

    fn main_rs(mut self) -> String {
        let ir = self.ir;
        let o = &mut self.out;
        o.line(&format!(
            "//! Generated by elanc-rs from {}.ref: do not edit.",
            ir.program
        ));
        o.line("//!");
        o.line("//! Normalisation (innermost) of the start term with the unlabelled rules;");
        o.line("//! one function per operator, its arguments in normal form.");
        o.line("#![allow(unused, dead_code, non_snake_case, non_camel_case_types)]");
        o.line("#![allow(unreachable_code, unreachable_patterns, irrefutable_let_patterns)]");
        o.line("#![allow(clippy::all)]");
        o.line("");
        o.line("use elan_runtime::builtin::{self, Builtin, Int, Str};");
        o.line("use elan_runtime::print::{Print, StringStyle, Writer};");
        o.line("use elan_runtime::{impl_sort, step, H};");
        o.line("");
        self.sorts();
        self.families();
        o_ops(&mut self);
        self.main_fn();
        self.out.buf
    }

    fn print_body(&mut self, o: OpId, fields: &[String]) {
        let op = &self.ir.ops[o];
        for it in &op.print {
            let l = match it {
                PrintItem::Arg(i) => format!("{}.print(w);", fields[*i]),
                PrintItem::Ident(s) => format!("w.ident({s:?});"),
                PrintItem::Char(c) => format!("w.ch({c:?});"),
                PrintItem::Num(n) => format!("w.num_code({n});"),
            };
            self.out.line(&l);
        }
    }

    /// An enum with the variants of `ops` and its Print impl.
    fn enum_def(&mut self, name: &str, doc: &str, variants: &[OpId]) {
        let ir = self.ir;
        self.out.comment("///", doc);
        self.out.line("#[derive(PartialEq, Eq, Hash, Debug)]");
        self.out.open(&format!("pub enum {name} {{"));
        for &v in variants {
            let op = &ir.ops[v];
            let why = match op.kind {
                OpKind::Constructor => "",
                _ => " (stuck: no rule applies)",
            };
            self.out.line(&format!("/// {}{why}", op.decl));
            let vn = op.variant.as_ref().unwrap();
            if op.args.is_empty() {
                self.out.line(&format!("{vn},"));
            } else {
                let tys: Vec<String> = op.args.iter().map(|&a| self.ty(a)).collect();
                self.out.line(&format!("{vn}({}),", tys.join(", ")));
            }
        }
        self.out.close("}");
        self.out.line(&format!("impl_sort!({name});"));
        self.out.line("");
        self.out.open(&format!("impl Print for {name} {{"));
        self.out.open("fn print(&self, w: &mut Writer) {");
        if variants.is_empty() {
            self.out.line("match *self {}");
        } else {
            self.out.open("match self {");
            for &v in variants {
                let op = &ir.ops[v];
                let vn = op.variant.as_ref().unwrap();
                let fields: Vec<String> = (0..op.args.len()).map(|i| format!("x{i}")).collect();
                if fields.is_empty() {
                    self.out.open(&format!("{name}::{vn} => {{"));
                } else {
                    self.out
                        .open(&format!("{name}::{vn}({}) => {{", fields.join(", ")));
                }
                self.print_body(v, &fields);
                self.out.close("}");
            }
            self.out.close("}");
        }
        self.out.close("}");
        self.out.close("}");
        self.out.line("");
    }

    fn sorts(&mut self) {
        let ir = self.ir;
        self.out
            .line("// ==== sorts ==================================================");
        self.out.line("");
        for (sid, s) in ir.sorts.iter().enumerate() {
            match &s.repr {
                Repr::Enum { variants } => {
                    let doc = format!("sort {}", s.name);
                    self.enum_def(&s.type_name, &doc, variants);
                }
                Repr::Family(f) => {
                    let how = if ir.families[*f].base == sid {
                        "builtin"
                    } else {
                        "injection of a builtin sort"
                    };
                    let t = self.ty(sid);
                    self.out.line(&format!("// sort {} ({how}): {t}", s.name));
                }
            }
        }
        self.out.line("");
    }

    fn families(&mut self) {
        let ir = self.ir;
        for fam in &ir.families {
            let Some(e) = &fam.stuck else { continue };
            let members: Vec<&str> = fam
                .members
                .iter()
                .map(|&m| ir.sorts[m].name.as_str())
                .collect();
            self.out.line(&format!(
                "/// A term of sort {}: a value or a stuck term.",
                members.join(", ")
            ));
            self.out.line(&format!(
                "pub type {} = Builtin<{}, H<{}>>;",
                e.alias,
                Self::native(fam.kind),
                e.type_name
            ));
            self.out.line("");
            let doc = format!(
                "Stuck terms of the sorts {} (a value is `Builtin::Val`).",
                members.join(", ")
            );
            self.enum_def(&e.type_name, &doc, &e.variants);
            self.out.open(&format!("impl {} {{", e.type_name));
            self.out.line("/// The ELAN sort (index) of the term.");
            self.out.open("pub fn sort(&self) -> u32 {");
            if e.variants.is_empty() {
                self.out.line("match *self {}");
            } else {
                self.out.open("match self {");
                for &v in &e.variants {
                    let op = &ir.ops[v];
                    let pat = if op.args.is_empty() { "" } else { "(..)" };
                    self.out.line(&format!(
                        "{}::{}{pat} => {},",
                        e.type_name,
                        op.variant.as_ref().unwrap(),
                        ir.sorts[op.result].index
                    ));
                }
                self.out.close("}");
            }
            self.out.close("}");
            self.out.close("}");
            self.out.line("");
        }
    }

    fn signature(&self, o: OpId) -> String {
        let op = &self.ir.ops[o];
        let params: Vec<String> = op
            .args
            .iter()
            .enumerate()
            .map(|(i, &a)| format!("a{i}: &{}", self.ty(a)))
            .collect();
        format!(
            "pub fn {}({}) -> {}",
            op.fun,
            params.join(", "),
            self.ty(op.result)
        )
    }

    fn op_fn(&mut self, o: OpId) {
        let ir = self.ir;
        let op = &ir.ops[o];
        let args: Vec<String> = (0..op.args.len()).map(|i| format!("a{i}")).collect();
        self.fresh = 0;
        match &op.kind {
            OpKind::Constructor => {
                self.out.line(&format!("/// {} (constructor)", op.decl));
                self.out.open(&format!("{} {{", self.signature(o)));
                let b = self.build_variant(o, &args);
                self.out.line(&b);
                self.out.close("}");
            }
            OpKind::Injection => {
                self.out
                    .line(&format!("/// {} (injection: the identity)", op.decl));
                self.out.open(&format!("{} {{", self.signature(o)));
                self.out.line("a0.clone()");
                self.out.close("}");
            }
            OpKind::BoolConst(b) => {
                self.out.line(&format!("/// {}", op.decl));
                self.out.open(&format!("{} {{", self.signature(o)));
                let v = self.wrap(op.result, if *b { "true" } else { "false" });
                self.out.line(&v);
                self.out.close("}");
            }
            OpKind::Builtin { op: b, total } => {
                self.out.line(&format!(
                    "/// {} (builtin {:?}{})",
                    op.decl,
                    b,
                    if *total { "" } else { ", may stay stuck" }
                ));
                self.out.open(&format!("{} {{", self.signature(o)));
                self.builtin_body(o, *b, *total, &args);
                self.out.close("}");
            }
            OpKind::Defined {
                rules,
                skipped,
                tree,
                total,
            } => {
                self.out.line(&format!(
                    "/// {}{}",
                    op.decl,
                    if *total {
                        ""
                    } else {
                        " (stuck when no rule applies)"
                    }
                ));
                for r in rules {
                    self.out.line(&format!("/// {}", r.text));
                }
                for s in skipped {
                    self.out.line(&format!("/// skipped: {s}"));
                }
                self.out.open(&format!("{} {{", self.signature(o)));
                self.decision(tree, rules);
                if *total {
                    self.out.line(&format!(
                        "unreachable!(\"{}: no rule applies to a total operator\")",
                        op.fun
                    ));
                } else {
                    self.out
                        .line("// no rule applies: the term is a normal form");
                    let b = self.build_variant(o, &args);
                    self.out.line(&b);
                }
                self.out.close("}");
            }
        }
        self.out.line("");
    }

    fn builtin_body(&mut self, o: OpId, b: BuiltinOp, total: bool, args: &[String]) {
        let ir = self.ir;
        let op = &ir.ops[o];
        let stuck = if total {
            "unreachable!(\"a total builtin operation is stuck\")".to_string()
        } else {
            self.build_variant(o, args)
        };
        let res = op.result;
        let is_true = |e: &Self, i: usize| -> String {
            if e.wrapped(op.args[i]) {
                format!("matches!(a{i}, Builtin::Val(true))")
            } else {
                format!("*a{i}")
            }
        };
        if !b.needs_values() {
            let v = match b {
                BuiltinOp::TermEq => "a0 == a1".to_string(),
                BuiltinOp::TermNeq => "a0 != a1".to_string(),
                BuiltinOp::BoolAnd => format!("{} && {}", is_true(self, 0), is_true(self, 1)),
                BuiltinOp::BoolOr => format!("{} || {}", is_true(self, 0), is_true(self, 1)),
                BuiltinOp::BoolNot => format!("!{}", is_true(self, 0)),
                _ => unreachable!(),
            };
            let w = self.wrap(res, &format!("({v})"));
            self.out.line(&w);
            return;
        }
        for (i, &a) in op.args.iter().enumerate() {
            if self.wrapped(a) {
                self.out.open(&format!("let v{i} = match a{i} {{"));
                self.out.line("Builtin::Val(v) => v.clone(),");
                self.out
                    .line(&format!("Builtin::Stuck(_) => return {stuck},"));
                self.out.close("};");
            } else {
                self.out.line(&format!("let v{i} = a{i}.clone();"));
            }
        }
        use BuiltinOp::*;
        let value = match b {
            IntAdd => "builtin::int_add(v0, v1)".to_string(),
            IntSub => "builtin::int_sub(v0, v1)".to_string(),
            IntMul => "builtin::int_mul(v0, v1)".to_string(),
            IntDiv => "builtin::int_div(v0, v1)".to_string(),
            IntRem => "builtin::int_rem(v0, v1)".to_string(),
            IntAnd => "builtin::int_and(v0, v1)".to_string(),
            IntOr => "builtin::int_or(v0, v1)".to_string(),
            IntNeg => "builtin::int_neg(v0)".to_string(),
            Cmp(c) => {
                let s = match c {
                    CmpOp::Eq => "==",
                    CmpOp::Ne => "!=",
                    CmpOp::Lt => "<",
                    CmpOp::Le => "<=",
                    CmpOp::Gt => ">",
                    CmpOp::Ge => ">=",
                };
                format!("(v0 as Int) {s} (v1 as Int)")
            }
            StrLen => "builtin::str_len(&v0)".to_string(),
            StrCat => "builtin::str_cat(&v0, &v1)".to_string(),
            StrIndex => "builtin::str_index(&v0, v1)".to_string(),
            StrModif => "builtin::str_modif(&v0, v1, v2)".to_string(),
            StrSubstr => "builtin::str_substr(&v0, v1, v2)".to_string(),
            StrSpn => "builtin::str_spn(&v0, &v1)".to_string(),
            StrCmp => "builtin::str_cmp(&v0, &v1)".to_string(),
            StrOfChar => "builtin::str_of_char(v0)".to_string(),
            TermEq | TermNeq | BoolAnd | BoolOr | BoolNot => unreachable!(),
        };
        if b.partial() {
            self.out.open(&format!("match {value} {{"));
            let w = self.wrap(res, "r");
            self.out.line(&format!("Some(r) => {w},"));
            self.out.line(&format!("None => {stuck},"));
            self.out.close("}");
        } else {
            let w = self.wrap(res, &value);
            self.out.line(&w);
        }
    }

    // ------------------------------------------------------------------
    // Decision trees and rules
    // ------------------------------------------------------------------

    fn decision(&mut self, d: &Decision, rules: &[RuleIr]) {
        match d {
            Decision::Fail => {}
            Decision::Try {
                rule,
                bindings,
                next,
            } => {
                self.try_rule(*rule, bindings, rules);
                self.decision(next, rules);
            }
            Decision::Switch {
                occ,
                sort,
                cases,
                default,
            } => match &self.ir.sorts[*sort].repr {
                Repr::Enum { .. } => self.enum_switch(occ, *sort, cases, default, rules),
                Repr::Family(_) => self.family_switch(occ, *sort, cases, default, rules),
            },
        }
    }

    fn enum_switch(
        &mut self,
        occ: &Occ,
        sort: SortId,
        cases: &[(Head, Decision)],
        default: &Option<Box<Decision>>,
        rules: &[RuleIr],
    ) {
        let ir = self.ir;
        let en = &ir.sorts[sort].type_name;
        let name = occ_name(occ);
        self.out.open(&format!("match &**{name} {{"));
        for (h, d) in cases {
            let Head::Op(o) = h else {
                unreachable!("literal in an enum sort")
            };
            let op = &ir.ops[*o];
            let vn = op.variant.as_ref().expect("case without variant");
            let fields: Vec<String> = (0..op.args.len())
                .map(|i| {
                    let mut c = occ.clone();
                    c.push(i);
                    occ_name(&c)
                })
                .collect();
            if fields.is_empty() {
                self.out.open(&format!("{en}::{vn} => {{"));
            } else {
                self.out
                    .open(&format!("{en}::{vn}({}) => {{", fields.join(", ")));
            }
            self.decision(d, rules);
            self.out.close("}");
        }
        match default.as_deref() {
            None => {}
            Some(Decision::Fail) => self.out.line("_ => {}"),
            Some(d) => {
                self.out.open("_ => {");
                self.decision(d, rules);
                self.out.close("}");
            }
        }
        self.out.close("}");
    }

    fn family_switch(
        &mut self,
        occ: &Occ,
        sort: SortId,
        cases: &[(Head, Decision)],
        default: &Option<Box<Decision>>,
        rules: &[RuleIr],
    ) {
        let ir = self.ir;
        let name = occ_name(occ);
        let label = format!("'s{}", self.next());
        self.out.open(&format!("{label}: {{"));
        for (h, d) in cases {
            let mut closes = 1;
            match h {
                Head::Int(_) | Head::Str(_) => {
                    let t = self.lit_test(sort, &name, h);
                    self.out.open(&format!("if {t} {{"));
                }
                Head::Op(o) => {
                    let op = &ir.ops[*o];
                    match op.kind {
                        OpKind::BoolConst(_) => {
                            let t = self.lit_test(sort, &name, h);
                            self.out.open(&format!("if {t} {{"));
                        }
                        OpKind::Injection => {
                            if self.wrapped(sort) {
                                let t = self.inj_test(op.args[0], &name);
                                self.out.open(&format!("if {t} {{"));
                            } else {
                                self.out.open("{");
                            }
                            let mut c = occ.clone();
                            c.push(0);
                            self.out.line(&format!("let {} = {name};", occ_name(&c)));
                        }
                        _ => {
                            // a stuck term of the family
                            let (en, _) = self.variant_enum(*o);
                            let vn = op.variant.as_ref().expect("case without variant");
                            let s = format!("s{}", self.next());
                            self.out
                                .open(&format!("if let Builtin::Stuck({s}) = {name} {{"));
                            let fields: Vec<String> = (0..op.args.len())
                                .map(|i| {
                                    let mut c = occ.clone();
                                    c.push(i);
                                    occ_name(&c)
                                })
                                .collect();
                            let pat = if fields.is_empty() {
                                format!("{en}::{vn}")
                            } else {
                                format!("{en}::{vn}({})", fields.join(", "))
                            };
                            self.out.open(&format!("if let {pat} = &**{s} {{"));
                            closes = 2;
                        }
                    }
                }
            }
            self.decision(d, rules);
            self.out.line(&format!("break {label};"));
            for _ in 0..closes {
                self.out.close("}");
            }
        }
        if let Some(d) = default {
            self.decision(d, rules);
        }
        self.out.close("}");
    }

    fn try_rule(&mut self, r: RuleId, bindings: &[(VarId, Occ)], rules: &[RuleIr]) {
        let rule = &rules[r];
        let label = format!("'r{}", self.next());
        self.out.line(&format!("// {}", rule.text));
        self.out.open(&format!("{label}: {{"));
        for (v, occ) in bindings {
            self.out
                .line(&format!("let {} = {};", rule.vars[*v].name, occ_name(occ)));
        }
        for c in &rule.conds {
            match c {
                Cond::Same(a, b) => {
                    self.out.line(&format!(
                        "if {} != {} {{ break {label}; }}",
                        rule.vars[*a].name, rule.vars[*b].name
                    ));
                }
                Cond::If(e) => {
                    let ex = self.expr(e, &rule.vars);
                    let bool_sort = self.expr_sort(e, &rule.vars);
                    let t = if self.wrapped(bool_sort) {
                        format!("!matches!({ex}, Builtin::Val(true))")
                    } else {
                        format!("!{ex}")
                    };
                    self.out.line(&format!("if {t} {{ break {label}; }}"));
                }
                Cond::Let(v, e) => {
                    let ex = self.expr(e, &rule.vars);
                    self.out
                        .line(&format!("let {} = &{ex};", rule.vars[*v].name));
                }
                Cond::Match(p, e) => {
                    let ex = self.expr(e, &rule.vars);
                    let s = self.expr_sort(e, &rule.vars);
                    let m = format!("m{}", self.next());
                    self.out.line(&format!("let {m} = &{ex};"));
                    self.pattern_check(p, &m, s, &label, &rule.vars);
                }
            }
        }
        self.out.line("step();");
        let rhs = self.expr(&rule.rhs, &rule.vars);
        self.out.line(&format!("return {rhs};"));
        self.out.close("}");
    }

    fn expr_sort(&self, e: &Expr, vars: &[VarIr]) -> SortId {
        match e {
            Expr::Var(v) => vars[*v].sort,
            Expr::Op { op, .. } => self.ir.ops[*op].result,
            Expr::Int(_) => self.int_sort().unwrap(),
            Expr::Str(_) => self.str_sort().unwrap(),
        }
    }

    /// Match the value at `scrut` (a reference of sort `s`) against `p`,
    /// binding its variables; `break label` when it does not match.
    fn pattern_check(&mut self, p: &Pattern, scrut: &str, s: SortId, label: &str, vars: &[VarIr]) {
        let ir = self.ir;
        match p {
            Pattern::Var(v) => self.out.line(&format!("let {} = {scrut};", vars[*v].name)),
            Pattern::Int(_) | Pattern::Str(_) => {
                let h = match p {
                    Pattern::Int(n) => Head::Int(*n),
                    Pattern::Str(x) => Head::Str(x.clone()),
                    _ => unreachable!(),
                };
                let t = self.lit_test(s, scrut, &h);
                self.out.line(&format!("if !({t}) {{ break {label}; }}"));
            }
            Pattern::Op { op, args } => {
                let o = &ir.ops[*op];
                match o.kind {
                    OpKind::BoolConst(_) => {
                        let t = self.lit_test(s, scrut, &Head::Op(*op));
                        self.out.line(&format!("if !({t}) {{ break {label}; }}"));
                    }
                    OpKind::Injection => {
                        if self.wrapped(s) {
                            let t = self.inj_test(o.args[0], scrut);
                            self.out.line(&format!("if !({t}) {{ break {label}; }}"));
                        }
                        self.pattern_check(&args[0], scrut, o.args[0], label, vars);
                    }
                    _ if o.variant.is_none() => {
                        self.out.line(&format!(
                            "break {label}; // {} is never a normal form",
                            o.decl
                        ));
                    }
                    _ => {
                        let (en, stuck) = self.variant_enum(*op);
                        let vn = o.variant.as_ref().unwrap();
                        let node = if stuck {
                            let st = format!("s{}", self.next());
                            self.out.line(&format!(
                                "let Builtin::Stuck({st}) = {scrut} else {{ break {label}; }};"
                            ));
                            st
                        } else {
                            scrut.to_string()
                        };
                        let fields: Vec<String> =
                            args.iter().map(|_| format!("p{}", self.next())).collect();
                        let pat = if fields.is_empty() {
                            format!("{en}::{vn}")
                        } else {
                            format!("{en}::{vn}({})", fields.join(", "))
                        };
                        self.out
                            .line(&format!("let {pat} = &**{node} else {{ break {label}; }};"));
                        for ((a, f), &as_) in args.iter().zip(&fields).zip(&o.args) {
                            self.pattern_check(a, f, as_, label, vars);
                        }
                    }
                }
            }
        }
    }

    fn main_fn(&mut self) {
        let ir = self.ir;
        self.out
            .line("// ==== main =====================================================");
        self.out.line("");
        self.out
            .line("/// `-noInput`: the start term of the query, normalised and printed.");
        self.out.open("fn main() {");
        self.out.open(&format!(
            "elan_runtime::main_program({:?}, |s| {{",
            ir.start.query_sort
        ));
        self.out.line("s.writer.string_style = StringStyle::Raw;");
        let e = self.expr(&ir.start.term, &[]);
        self.out
            .line(&format!("let t: {} = {e};", self.ty(ir.start.sort)));
        self.out.line("s.result(&t);");
        self.out.close("});");
        self.out.close("}");
    }
}

fn o_ops(e: &mut Emitter) {
    e.out
        .line("// ==== operators ==============================================");
    e.out.line("");
    for o in 0..e.ir.ops.len() {
        e.op_fn(o);
    }
}
