elanlibdir = $(datadir)/elanlib
commondir  = $(elanlibdir)/common

ELANLIB_COMMON = \
			Query.eln\
			anyIdentifier.eln\
			anyInteger.eln\
			anyQuotedIdentifier.eln\
			array.eln\
			arrayLIN.eln\
			arrayLOG.eln\
			bool.eln\
			builtinArray.eln\
			builtinHashTerm.eln\
			builtinIO.eln\
			IO.eln\
			builtinInt.eln\
			builtinStdio.eln\
			builtinString.eln\
			builtinSyntacticMatching.eln\
			cmp.eln\
			double.eln\
			doubleConstants.eln\
			eq.eln\
			identity.eln\
			int.eln\
			integerConstants.eln\
			list.eln\
			occur.eln\
			pair.eln\
			prompt.eln\
			replace.eln\
			stdio.eln\
			string.eln\
			strlist.eln\
			tuple.eln

EXTRA_DIST  = $(ELANLIB_COMMON)
common_DATA = $(ELANLIB_COMMON)

