#!/bin/tcsh
echo

#
# On peut donner ELANLIB en parametre
#
set ARCH = `uname -m`

#set ELANLIB = /users/protheo/pot/ELAN/version.3.0/elanlib
#
# on suppose que l'executable se trouve en ${ELANLIB}/../bin/${ARCH}/elan
#
set ELAN="${ELANLIB}/../bin/${ARCH}/elan"
#set ELAN="~borovan/elan/bin/${ARCH}/elan"

if(${ARCH} == alpha) then
  set CLASSPATH = /local/logiciels/langages/Java/alpha/lib/classes.zip
  set JAVA="/local/logiciels/langages/Java/alpha/bin/java"
else
  if(${ARCH} == i686) then
#    set CLASSPATH = /local/logiciels/langages/Java/linux/jdk1.1.6/lib/classes.zip
#    set JAVA = "/local/logiciels/langages/Java/linux/jdk1.1.6/bin/java"

# Pour RedHat 6.* utiliser la 1.2v2
    set CLASSPATH = /local/logiciels/langages/Java/linux/jdk1.2v2/lib/classes.zip
    set JAVA = "/local/logiciels/langages/Java/linux/jdk1.2v2/bin/java"
   else
    set CLASSPATH = /local/logiciels/langages/Java/java/lib/classes.zip
    set JAVA = "/local/logiciels/langages/Java/java/bin/java"
  endif
endif

set CLASSES="${ELANLIB}/Compiler/classes"
set REMOPTION=""
set ELANOPTION="-b "
set LGIFILE=""
set LGIDIR =""
set SPCFILE=""
set SPCDIR =""
set SPCNAME =""


set verb
if($#argv>0) then
  @ j=1
  foreach i ($argv)
#    echo $i
    switch ($i) 	
      case -nocode:
      case -nosplit:
      case -choicePointDebug:
      case -noOptimiseChoicePoint:
      case -optimiseChoicePoint:
      case -verbose:
      case -debug:
      case -color:
      case -noColor:
      case -withGoto:
      case -oldVariableAffectation:
      case -onlyC:
        set REMOPTION = "${REMOPTION} $i"
        breaksw
      case -quiet:
        set REMOPTION = "${REMOPTION} $i"
	unset verb
        breaksw
      case -ba*:
        set REMOPTION = "${REMOPTION} $i"
        breaksw
# option with argument
      case -strategy:
      case -output:
	set remarg
        set REMOPTION = "${REMOPTION} $i"
        breaksw
# option with argument
      case --trace: 
      case -t:
      case --elanlib:
      case --secondlib:
      case -l:
      case --output:
        set elanarg
        set ELANOPTION = "${ELANOPTION} $i"
        breaksw
      case -*:
        set ELANOPTION = "${ELANOPTION} $i"
        breaksw
      default:
	if($?remarg) then
          unset remarg
          set REMOPTION = "${REMOPTION} $i"
        else
  	  if($?elanarg) then
            unset elanarg
            set ELANOPTION = "${ELANOPTION} $i"
          else
            if($j < $#argv) then
              set LGIFILE = `basename $i .lgi`
              set LGIDIR  = `dirname $i`
            else
              if(${LGIFILE} != "") then
                set SPCFILE = `basename $i .spc`
                set SPCDIR  = `dirname $i`
	        set SPCNAME = ${SPCDIR}/${SPCFILE}.spc 
              else
                set LGIFILE = `basename $i .lgi`
                set LGIDIR  = `dirname $i`
              endif
            endif
          endif
        endif
     endsw
     @ j++
  end

  #echo "REMOPTION  = ${REMOPTION}"
  #echo "ELANOPTION = ${ELANOPTION}"
  #echo "LGIFILE    = ${LGIFILE}"
  #echo "SPCFILE    = ${SPCFILE}"

if($?verb) then
  echo ${ELAN} --cexport ${LGIFILE}.ref ${ELANOPTION} ${LGIDIR}/${LGIFILE}.lgi ${SPCNAME}
endif

  ${ELAN} --cexport ${LGIFILE}.ref ${ELANOPTION} ${LGIDIR}/${LGIFILE}.lgi ${SPCNAME}

if($?verb) then
  echo ${JAVA} -classpath ${CLASSPATH}:${CLASSES} REM ${LGIFILE}.ref ${REMOPTION}
endif

  ${JAVA} -classpath ${CLASSPATH}:${CLASSES} REM ${LGIFILE}.ref ${REMOPTION}
else
  echo "elanc [[elan options][compiler options]] file[.lgi] [file.[spc]]"
  ${JAVA} -classpath ${CLASSPATH}:${CLASSES} REM

#  echo "elanc [[elan options][-nosplit][-nocode][-quiet]] file[.lgi] [file.[spc]]"
#  echo "  [-nosplit]                  to produce only 2 files"
#  echo "  [-nocode]                   to erase generated files"
#  echo "  [-choicePointDebug]         to print choicePoints statistics"
#  echo "  [-noOptimiseChoicePoint]    to remove optimisation"
#  echo "  [-quiet]"
endif

