/* Generated By:JavaCC: Do not edit this line. REFParser.java */
import java.util.Vector;

public class REFParser implements REFParserConstants {

/*
TOKEN : {
 <IDENTIFIER: <LETTER> (<LETTER> | <DIGIT>)*>
|  <#LETTER: ["$","A"-"Z","_","a"-"z"]>
|  <#DIGIT: ["0"-"9"]>
}
*/
  static final public int readInt() throws ParseException {
  boolean negative = false;
  Token token;
  int res;
    switch (nextToken.kind) {
    case 20:
      jj_consume_token(20);
        negative=true;
      break;
    default:
      jj_expLA1[0] = jj_gen;
      ;
    }
    token = jj_consume_token(INTEGER);
    res = Integer.parseInt(token.image);
    if(negative)
      res = -res;
    if (true) return res;
    throw new Error("Missing return statement in function");
  }

  static final boolean[] jj_mask_0 = new boolean[58];
  static {
    jj_mask_0[20] = true;
  }
  
  static final public Query Start(OutputCode s) throws ParseException {
  Query query;
  int numberOfGrammarRule = 0;
    jj_consume_token(LEXEM_DECLARATION);
    LexemIdentifierDeclaration();
    switch (nextToken.kind) {
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_expLA1[2] = jj_gen;
      switch (nextToken.kind) {
      case COMMA:
        jj_consume_token(COMMA);
        break;
      default:
        jj_expLA1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    jj_consume_token(SORT_DECLARATION);
    LexemSortDeclaration();
    switch (nextToken.kind) {
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_expLA1[4] = jj_gen;
      switch (nextToken.kind) {
      case COMMA:
        jj_consume_token(COMMA);
        break;
      default:
        jj_expLA1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    jj_consume_token(MODULE_DECLARATION);
    LexemModuleDeclaration();
    switch (nextToken.kind) {
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_expLA1[6] = jj_gen;
      switch (nextToken.kind) {
      case COMMA:
        jj_consume_token(COMMA);
        break;
      default:
        jj_expLA1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    jj_consume_token(RULENAME_DECLARATION);
    LexemRuleNameDeclaration();
    switch (nextToken.kind) {
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_expLA1[8] = jj_gen;
      switch (nextToken.kind) {
      case COMMA:
        jj_consume_token(COMMA);
        break;
      default:
        jj_expLA1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    jj_consume_token(STRATEGYNAME_DECLARATION);
    LexemStrategyNameDeclaration();
    switch (nextToken.kind) {
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_expLA1[10] = jj_gen;
      switch (nextToken.kind) {
      case COMMA:
        jj_consume_token(COMMA);
        break;
      default:
        jj_expLA1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
        // Tables for Earley
      s.write("int gram[] = {\n");
    numberOfGrammarRule = GrammarDeclaration(s,numberOfGrammarRule);
    switch (nextToken.kind) {
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_expLA1[12] = jj_gen;
      switch (nextToken.kind) {
      case COMMA:
        jj_consume_token(COMMA);
        break;
      default:
        jj_expLA1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    numberOfGrammarRule = GrammarDeclaration(s,numberOfGrammarRule);
    switch (nextToken.kind) {
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_expLA1[14] = jj_gen;
      switch (nextToken.kind) {
      case COMMA:
        jj_consume_token(COMMA);
        break;
      default:
        jj_expLA1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    numberOfGrammarRule = GrammarDeclaration(s,numberOfGrammarRule);
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
        // Tables for Earley
      s.write("0};\n");
      s.write("int pos = " + numberOfGrammarRule + ";\n");
    switch (nextToken.kind) {
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_expLA1[16] = jj_gen;
      switch (nextToken.kind) {
      case COMMA:
        jj_consume_token(COMMA);
        break;
      default:
        jj_expLA1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    RuleDeclaration();
    switch (nextToken.kind) {
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_expLA1[18] = jj_gen;
      switch (nextToken.kind) {
      case COMMA:
        jj_consume_token(COMMA);
        break;
      default:
        jj_expLA1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    StrategyDeclaration();
    switch (nextToken.kind) {
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_expLA1[20] = jj_gen;
      switch (nextToken.kind) {
      case COMMA:
        jj_consume_token(COMMA);
        break;
      default:
        jj_expLA1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    query = QueryDeclaration();
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    switch (nextToken.kind) {
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_expLA1[21] = jj_gen;
      ;
    }
    jj_consume_token(0);
      if(!Flags.quiet && !Flags.debug) System.out.println("");
      if (true) return query;
    throw new Error("Missing return statement in function");
  }

  static final boolean[] jj_mask_1 = new boolean[58];
  static {
    jj_mask_1[COMMA] = true;
  }
  static final boolean[] jj_mask_2 = new boolean[58];
  static {
    jj_mask_2[END] = true;
  }
  static final boolean[] jj_mask_3 = new boolean[58];
  static {
    jj_mask_3[COMMA] = true;
  }
  static final boolean[] jj_mask_4 = new boolean[58];
  static {
    jj_mask_4[END] = true;
  }
  static final boolean[] jj_mask_5 = new boolean[58];
  static {
    jj_mask_5[COMMA] = true;
  }
  static final boolean[] jj_mask_6 = new boolean[58];
  static {
    jj_mask_6[END] = true;
  }
  static final boolean[] jj_mask_7 = new boolean[58];
  static {
    jj_mask_7[COMMA] = true;
  }
  static final boolean[] jj_mask_8 = new boolean[58];
  static {
    jj_mask_8[END] = true;
  }
  static final boolean[] jj_mask_9 = new boolean[58];
  static {
    jj_mask_9[COMMA] = true;
  }
  static final boolean[] jj_mask_10 = new boolean[58];
  static {
    jj_mask_10[END] = true;
  }
  static final boolean[] jj_mask_11 = new boolean[58];
  static {
    jj_mask_11[COMMA] = true;
  }
  static final boolean[] jj_mask_12 = new boolean[58];
  static {
    jj_mask_12[END] = true;
  }
  static final boolean[] jj_mask_13 = new boolean[58];
  static {
    jj_mask_13[COMMA] = true;
  }
  static final boolean[] jj_mask_14 = new boolean[58];
  static {
    jj_mask_14[END] = true;
  }
  static final boolean[] jj_mask_15 = new boolean[58];
  static {
    jj_mask_15[COMMA] = true;
  }
  static final boolean[] jj_mask_16 = new boolean[58];
  static {
    jj_mask_16[END] = true;
  }
  static final boolean[] jj_mask_17 = new boolean[58];
  static {
    jj_mask_17[COMMA] = true;
  }
  static final boolean[] jj_mask_18 = new boolean[58];
  static {
    jj_mask_18[END] = true;
  }
  static final boolean[] jj_mask_19 = new boolean[58];
  static {
    jj_mask_19[COMMA] = true;
  }
  static final boolean[] jj_mask_20 = new boolean[58];
  static {
    jj_mask_20[END] = true;
  }
  static final boolean[] jj_mask_21 = new boolean[58];
  static {
    jj_mask_21[END] = true;
  }
  
  static final public void LexemIdentifierDeclaration() throws ParseException {
  Token tokenId;
  int id;
  String lexName;
  Lexem lex;
    label_1:
    while (true) {
      switch (nextToken.kind) {
      case INTEGER:
      case 20:
        ;
        break;
      default:
        jj_expLA1[22] = jj_gen;
        break label_1;
      }
      id = readInt();
      jj_consume_token(21);
      tokenId = jj_consume_token(STRING_LITERAL);
      jj_consume_token(DOT);
      lexName = tokenId.image.substring(1,tokenId.image.length()-1);
      lex = new LexemIdentifier( id, lexName );
      lex.put();
    }
    jj_consume_token(NIL);
  }

  static final boolean[] jj_mask_22 = new boolean[58];
  static {
    jj_mask_22[INTEGER] =
    jj_mask_22[20] = true;
  }
  
  static final public void LexemSortDeclaration() throws ParseException {
  Token tokenId;
  int id;
  String lexName;
  Lexem lex;
    label_2:
    while (true) {
      switch (nextToken.kind) {
      case INTEGER:
      case 20:
        ;
        break;
      default:
        jj_expLA1[23] = jj_gen;
        break label_2;
      }
      id = readInt();
      jj_consume_token(21);
      tokenId = jj_consume_token(STRING_LITERAL);
      jj_consume_token(DOT);
      lexName = tokenId.image.substring(1,tokenId.image.length()-1);
      lex = new LexemSort( id, lexName );
      lex.put();
    }
    jj_consume_token(NIL);
  }

  static final boolean[] jj_mask_23 = new boolean[58];
  static {
    jj_mask_23[INTEGER] =
    jj_mask_23[20] = true;
  }
  
  static final public void LexemModuleDeclaration() throws ParseException {
  Token tokenId;
  int id;
  String lexName;
  Lexem lex;
    label_3:
    while (true) {
      switch (nextToken.kind) {
      case INTEGER:
      case 20:
        ;
        break;
      default:
        jj_expLA1[24] = jj_gen;
        break label_3;
      }
      id = readInt();
      jj_consume_token(21);
      tokenId = jj_consume_token(STRING_LITERAL);
      jj_consume_token(DOT);
      lexName = tokenId.image.substring(1,tokenId.image.length()-1);
      lex = new LexemModule( id, lexName );
      lex.put();
    }
    jj_consume_token(NIL);
  }

  static final boolean[] jj_mask_24 = new boolean[58];
  static {
    jj_mask_24[INTEGER] =
    jj_mask_24[20] = true;
  }
  
  static final public void LexemRuleNameDeclaration() throws ParseException {
  Token tokenId;
  int id;
  String lexName;
  Lexem lex;
    label_4:
    while (true) {
      switch (nextToken.kind) {
      case INTEGER:
      case 20:
        ;
        break;
      default:
        jj_expLA1[25] = jj_gen;
        break label_4;
      }
      id = readInt();
      jj_consume_token(21);
      tokenId = jj_consume_token(STRING_LITERAL);
      jj_consume_token(DOT);
      lexName = tokenId.image.substring(1,tokenId.image.length()-1);
      lex = new LexemRuleName( id, lexName );
      lex.put();
    }
    jj_consume_token(NIL);
  }

  static final boolean[] jj_mask_25 = new boolean[58];
  static {
    jj_mask_25[INTEGER] =
    jj_mask_25[20] = true;
  }
  
  static final public void LexemStrategyNameDeclaration() throws ParseException {
  Token tokenId;
  int id;
  String lexName;
  Lexem lex;
    label_5:
    while (true) {
      switch (nextToken.kind) {
      case INTEGER:
      case 20:
        ;
        break;
      default:
        jj_expLA1[26] = jj_gen;
        break label_5;
      }
      id = readInt();
      jj_consume_token(21);
      tokenId = jj_consume_token(STRING_LITERAL);
      jj_consume_token(DOT);
      lexName = tokenId.image.substring(1,tokenId.image.length()-1);
      lex = new LexemStrategyName( id, lexName );
      lex.put();
    }
    jj_consume_token(NIL);
  }

  static final boolean[] jj_mask_26 = new boolean[58];
  static {
    jj_mask_26[INTEGER] =
    jj_mask_26[20] = true;
  }
  
  static final public int GrammarDeclaration(OutputCode s,int numberOfGrammarRule) throws ParseException {
  int idSort;
  int isBuiltin;
  LexemSort lexSort;
    label_6:
    while (true) {
      switch (nextToken.kind) {
      case 22:
        ;
        break;
      default:
        jj_expLA1[27] = jj_gen;
        break label_6;
      }
      jj_consume_token(22);
      idSort = readInt();
      jj_consume_token(21);
      isBuiltin = readInt();
      jj_consume_token(21);
       lexSort = LexemSort.get(idSort);
       if(isBuiltin==1) {
          lexSort.setBuiltin();
       }
      label_7:
      while (true) {
        switch (nextToken.kind) {
        case INTEGER:
        case 20:
          ;
          break;
        default:
          jj_expLA1[28] = jj_gen;
          break label_7;
        }
        numberOfGrammarRule = SymbolDeclaration(lexSort,s,numberOfGrammarRule);
        jj_consume_token(DOT);
      }
      jj_consume_token(NIL);
      switch (nextToken.kind) {
      case END:
        jj_consume_token(END);
        break;
      default:
        jj_expLA1[30] = jj_gen;
        switch (nextToken.kind) {
        case DOT:
          jj_consume_token(DOT);
          break;
        default:
          jj_expLA1[29] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    jj_consume_token(ENDDEF);
        if (true) return numberOfGrammarRule;
    throw new Error("Missing return statement in function");
  }

  static final boolean[] jj_mask_27 = new boolean[58];
  static {
    jj_mask_27[22] = true;
  }
  static final boolean[] jj_mask_28 = new boolean[58];
  static {
    jj_mask_28[INTEGER] =
    jj_mask_28[20] = true;
  }
  static final boolean[] jj_mask_29 = new boolean[58];
  static {
    jj_mask_29[DOT] = true;
  }
  static final boolean[] jj_mask_30 = new boolean[58];
  static {
    jj_mask_30[END] = true;
  }
  
  static final public int SymbolDeclaration(Lexem lexSort, OutputCode s,int numberOfGrammarRule) throws ParseException {
  int intGrammar;
  int intSym;
  int intArity;
  int intInfo;
  int intSemantic;
  int intStrategy;
  int intTheory;
  int intLocStrat;

  Symbol sym;
  Lexem lexem;
  Vector vectorLex = new Vector(10);
  Lexem[] arrayLex;
    // for Earley tables
  int i,type;
  int vectorLexSize = 0;
    intGrammar = readInt();
    jj_consume_token(21);
    // unused
      intSym = readInt();
    jj_consume_token(21);
    intArity = readInt();
    jj_consume_token(21);
    // unused
      intInfo = readInt();
    jj_consume_token(21);
    // unused
      intSemantic = readInt();
    jj_consume_token(21);
    intTheory = readInt();
    jj_consume_token(21);
    intStrategy = readInt();
    jj_consume_token(21);
    label_8:
    while (true) {
      lexem = ALexem();
      jj_consume_token(DOT);
         vectorLex.addElement(lexem);
        if (lexem != LexemIdentifier.blank) {
          vectorLexSize++;
        }
      switch (nextToken.kind) {
      case 23:
      case 25:
      case 26:
      case 27:
      case 28:
        ;
        break;
      default:
        jj_expLA1[31] = jj_gen;
        break label_8;
      }
    }
    jj_consume_token(NIL);
    jj_consume_token(21);
    label_9:
    while (true) {
      switch (nextToken.kind) {
      case INTEGER:
      case 20:
        ;
        break;
      default:
        jj_expLA1[32] = jj_gen;
        break label_9;
      }
      intLocStrat = readInt();
      jj_consume_token(DOT);

    }
    jj_consume_token(NIL);
      arrayLex = new Lexem[vectorLex.size()];
      vectorLex.copyInto(arrayLex);
      vectorLex.removeAllElements();

        /*
         * Generation des tableaux pour Earley
         */
        // Global Rule
      s.write("1,");
      int info = intArity+(intInfo*(007777+1));
      s.write(info + ",");
      s.write(intSym + ",");
      s.write(lexSort.getCode() + ",");
      s.write(vectorLexSize + ",");

      numberOfGrammarRule += 5;
      for(i=0 ; i<arrayLex.length ; i++) {
        lexem = (Lexem)arrayLex[i];
        if(lexem != LexemIdentifier.blank) {
            // Type
          if(lexem instanceof LexemIdentifier) type = 0;
          else if(lexem instanceof LexemSort) type = 1;
          else if(lexem instanceof LexemChar) type = 2;
          else if(lexem instanceof LexemNum) type = 3;
          else           if (true) throw new InternalError("Wrong lexem in REF file");
          s.write(type + ",");
          s.write(lexem.getCode() + ",");
          numberOfGrammarRule += 2;
        }
      }
      s.write("\n");

      if(Flags.strat > 0 && intStrategy != 0) {          // Peter
         if (ElanConstants.isFsym(intStrategy)) {
           sym = new SymbolFsym(intSym,arrayLex,lexSort,intSemantic,intStrategy);
           sym.put(); }
         else if (ElanConstants.isLab(intStrategy)) {
           sym = new SymbolLab(intSym,arrayLex,lexSort,intSemantic,intStrategy);
           sym.put(); }
         else if (ElanConstants.isApply(intStrategy)) {
           sym = new SymbolApply(intSym,arrayLex,lexSort,intSemantic,intStrategy);
           sym.put(); }
         else { // if (ElanConstants.isDstr(intStrategy))
           sym = new SymbolDstr(intSym,arrayLex,lexSort,intSemantic,intStrategy);
           sym.put(); }                                          // Peter
      } else if( intSemantic != 0 ) {
         sym = new SymbolBuiltin(intSym,arrayLex,lexSort,intSemantic,intTheory);
         sym.put();
         if(intSemantic<0 && Symbol.get(-intSemantic)==null) {
           sym = new SymbolBuiltin(-intSemantic,arrayLex,lexSort,-intSemantic,intTheory);
           sym.put();
         }
      } else if( intTheory == 0 ) {
         sym = new SymbolFree(intSym,arrayLex,lexSort);
         sym.put();
      } else if( intTheory == 2 ) {
         sym = new SymbolAC(intSym,arrayLex,lexSort);
         sym.put();
      }
      if (true) return numberOfGrammarRule;
    throw new Error("Missing return statement in function");
  }

  static final boolean[] jj_mask_31 = new boolean[58];
  static {
    jj_mask_31[23] =
    jj_mask_31[25] =
    jj_mask_31[26] =
    jj_mask_31[27] =
    jj_mask_31[28] = true;
  }
  static final boolean[] jj_mask_32 = new boolean[58];
  static {
    jj_mask_32[INTEGER] =
    jj_mask_32[20] = true;
  }
  
  static final public Lexem ALexem() throws ParseException {
  Lexem lex;
  int id;
    switch (nextToken.kind) {
    case 23:
      jj_consume_token(23);
      id = readInt();
      jj_consume_token(24);
      if (true) return LexemIdentifier.get(id);
      break;
    default:
      jj_expLA1[37] = jj_gen;
      switch (nextToken.kind) {
      case 25:
        jj_consume_token(25);
        id = readInt();
        jj_consume_token(24);
      if (true) return LexemSort.get(id);
        break;
      default:
        jj_expLA1[36] = jj_gen;
        switch (nextToken.kind) {
        case 26:
          jj_consume_token(26);
          id = readInt();
          jj_consume_token(24);
      lex=LexemChar.get(id);
      if(lex==null) {
         lex = new LexemChar(id);
         lex.put();
      }
      if (true) return lex;
          break;
        default:
          jj_expLA1[35] = jj_gen;
          switch (nextToken.kind) {
          case 27:
            jj_consume_token(27);
            id = readInt();
            jj_consume_token(24);
      lex=LexemNum.get(id);
      if(lex==null) {
         lex = new LexemNum(id);
         lex.put();
      }
      if (true) return lex;
            break;
          default:
            jj_expLA1[34] = jj_gen;
            switch (nextToken.kind) {
            case 28:
              jj_consume_token(28);
      if (true) return LexemIdentifier.blank;
              break;
            default:
              jj_expLA1[33] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  static final boolean[] jj_mask_33 = new boolean[58];
  static {
    jj_mask_33[28] = true;
  }
  static final boolean[] jj_mask_34 = new boolean[58];
  static {
    jj_mask_34[27] = true;
  }
  static final boolean[] jj_mask_35 = new boolean[58];
  static {
    jj_mask_35[26] = true;
  }
  static final boolean[] jj_mask_36 = new boolean[58];
  static {
    jj_mask_36[25] = true;
  }
  static final boolean[] jj_mask_37 = new boolean[58];
  static {
    jj_mask_37[23] = true;
  }
  
  static final public void RuleDeclaration() throws ParseException {
  int intModule;
  int intInfo;
  int intAC;
  int intVarNum;

  Term leftside;
  Term rightside;
  RightHandSide rightsideOldSwitch;
  BranchEvaluation wheres;
  Lexem ruleName=null;
  Lexem ruleSort;
  int idSort;
  RewriteRule rule;
  int id;
  int ruleNameIndex;
  int i;
  LineariseCondition linearConditions;
    label_10:
    while (true) {
      switch (nextToken.kind) {
      case 29:
        jj_consume_token(29);
        ruleNameIndex = readInt();
        jj_consume_token(COMMA);
         if( ruleNameIndex != -1 ) {
           ruleName = LexemRuleName.get(ruleNameIndex);
         } else {
           ruleName = null;
         }
        idSort = readInt();
        jj_consume_token(COMMA);
        intModule = readInt();
        jj_consume_token(COMMA);
        intInfo = readInt();
        jj_consume_token(COMMA);
        intAC = readInt();
        jj_consume_token(COMMA);
        /*
               * Nombre de variables apparaissant dans la regle a quoi ca sert ?
               * [pem: May 20 99] je m'en sert pour normaliser les lhs
               * et les localAffectation
               */
            intVarNum = readInt();
        jj_consume_token(COMMA);
      linearConditions = new LineariseCondition();
      linearConditions.updateMaxVariableNumber(intVarNum);
        leftside = unflattenedElanTerm();
        jj_consume_token(COMMA);
        rightside = ElanTerm();
        jj_consume_token(COMMA);
        wheres = Wheres(linearConditions);
        jj_consume_token(24);
        switch (nextToken.kind) {
        case END:
          jj_consume_token(END);
          break;
        default:
          jj_expLA1[42] = jj_gen;
          switch (nextToken.kind) {
          case DOT:
            jj_consume_token(DOT);
            break;
          default:
            jj_expLA1[41] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
        //System.out.println("intVarNum = " + intVarNum);


      if(!Flags.quiet && !Flags.debug) {
         //System.out.print(".");
      }
      ruleSort = LexemSort.get(idSort);


        /*
         * mise en ONF
         */
      leftside.flatten();
      leftside.orderedNormalForm();

        /*
         * Linearise leftside
         */
      leftside.linearise(linearConditions);
      if(Flags.debug && linearConditions.getConditions().size()>0) {
        System.out.println("linearise lhs: " + leftside);
      }

      for(i=0 ; i<linearConditions.getConditions().size() ; i++) {
         // insertion en tete	
         wheres.insertLocalEvaluation((LocalEvaluation)
                                     linearConditions.conditionAt(i));
      }
      linearConditions.removeAllConditions();

      rule = new RewriteRule(ruleName,ruleSort,leftside,
                              new RhsTerm(rightside,wheres),wheres);
      try{
         if(rule.isCompilable()) {
           RewriteRule.addElement(rule);
         }
      } catch (ACPatternNotCompiled e) {
         if(!Flags.quiet) {
           System.out.println("\nWarning: " + leftside);
          System.out.println("This pattern is not compiled");
         }
      } catch (CompileError e) {
        System.out.println("\nError: " + leftside);
        System.out.println("This pattern cannot be compiled");
        System.out.println("Please, apply a program transformation as described in the manual");
        System.exit(1);
      }
        break;
      default:
        jj_expLA1[43] = jj_gen;
        switch (nextToken.kind) {
        case 30:
          jj_consume_token(30);
          ruleNameIndex = readInt();
          jj_consume_token(COMMA);
         if( ruleNameIndex != -1 ) {
           ruleName = LexemRuleName.get(ruleNameIndex);
         } else {
           ruleName = null;
         }
          idSort = readInt();
          jj_consume_token(COMMA);
          intModule = readInt();
          jj_consume_token(COMMA);
          intInfo = readInt();
          jj_consume_token(COMMA);
          intAC = readInt();
          jj_consume_token(COMMA);
          // Nombre de variables apparaissant dans la regle a quoi ca sert ???
              intVarNum = readInt();
          jj_consume_token(COMMA);
      linearConditions = new LineariseCondition();
      linearConditions.updateMaxVariableNumber(intVarNum);
          leftside = unflattenedElanTerm();
          jj_consume_token(COMMA);
          rightsideOldSwitch = ElanRightHandSide(linearConditions);
          jj_consume_token(24);
          switch (nextToken.kind) {
          case END:
            jj_consume_token(END);
            break;
          default:
            jj_expLA1[39] = jj_gen;
            switch (nextToken.kind) {
            case DOT:
              jj_consume_token(DOT);
              break;
            default:
              jj_expLA1[38] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
      ruleSort = LexemSort.get(idSort);
      wheres = rightsideOldSwitch.getBranch();
      /*
       * Linearise rule
       */
      leftside.linearise(linearConditions);
      for(i=0 ; i<linearConditions.getConditions().size() ; i++) {
         // insertion en tete	
         wheres.insertLocalEvaluation((LocalEvaluation)
                                     linearConditions.conditionAt(i));
      }
      linearConditions.removeAllConditions();

      leftside.flatten();
      leftside.orderedNormalForm();
      rule = new RewriteRule(ruleName,ruleSort,leftside,rightsideOldSwitch,wheres);
      try{
         if(rule.isCompilable()) {
           RewriteRule.addElement(rule);
         }
      } catch (CompileError e) {
         if(!Flags.quiet && Flags.debug) {
           System.out.println("cannot be compile: " + leftside);
         }
      }
          break;
        default:
          jj_expLA1[40] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      switch (nextToken.kind) {
      case 29:
      case 30:
        ;
        break;
      default:
        jj_expLA1[44] = jj_gen;
        break label_10;
      }
    }
    jj_consume_token(ENDDEF);
  }

  static final boolean[] jj_mask_38 = new boolean[58];
  static {
    jj_mask_38[DOT] = true;
  }
  static final boolean[] jj_mask_39 = new boolean[58];
  static {
    jj_mask_39[END] = true;
  }
  static final boolean[] jj_mask_40 = new boolean[58];
  static {
    jj_mask_40[30] = true;
  }
  static final boolean[] jj_mask_41 = new boolean[58];
  static {
    jj_mask_41[DOT] = true;
  }
  static final boolean[] jj_mask_42 = new boolean[58];
  static {
    jj_mask_42[END] = true;
  }
  static final boolean[] jj_mask_43 = new boolean[58];
  static {
    jj_mask_43[29] = true;
  }
  static final boolean[] jj_mask_44 = new boolean[58];
  static {
    jj_mask_44[29] =
    jj_mask_44[30] = true;
  }
  
  static final public Term ElanTerm() throws ParseException {
  Term term;
    term = BuildElanTerm();
      //System.out.println("term before flatten = " + term);
      term.flatten();
      term.orderedNormalForm();
      if (true) return term;
    throw new Error("Missing return statement in function");
  }

  static final public Term unflattenedElanTerm() throws ParseException {
  Term term;
    term = BuildElanTerm();
      if (true) return term;
    throw new Error("Missing return statement in function");
  }

  static final public Term BuildElanTerm() throws ParseException {
  Symbol symbol;
  Lexem lex;
  Lexem sort;
  Vector subterms=null;
  int idFsym;
  int idVar;
  int idSort;
  Object value;
  int intValue;
  String stringValue;
    switch (nextToken.kind) {
    case 31:
      jj_consume_token(31);
      subterms = ElanTerms();
      jj_consume_token(COMMA);
      idFsym = readInt();
      jj_consume_token(24);
      symbol=Symbol.get(idFsym);
      if(symbol == null) {
         if (true) throw new InternalError("symbol sym" + idFsym + " not found");
      }
      if (true) return new Term(symbol,subterms);
      break;
    default:
      jj_expLA1[50] = jj_gen;
      switch (nextToken.kind) {
      case 32:
        jj_consume_token(32);
        idVar = readInt();
        jj_consume_token(COMMA);
        idSort = readInt();
        jj_consume_token(24);
      // Creation eventuelle du lexem
      sort   = LexemSort.get(idSort);
      //if(sort==null) {
      //System.out.println("ERREUR VAR idVar=" + idVar + " idSort=" + idSort);
      //}

      lex   = LexemVariableName.get(idVar);
      if(lex==null) {
         lex = new LexemVariableName(idVar, "var"+idVar);
         lex.put();
      }
      symbol=SymbolVariable.getCreate(idVar,sort);
      if (true) return new Term(symbol,subterms);
        break;
      default:
        jj_expLA1[49] = jj_gen;
        switch (nextToken.kind) {
        case 33:
          jj_consume_token(33);
          idVar = readInt();
          jj_consume_token(COMMA);
          idSort = readInt();
          jj_consume_token(24);
      // Creation eventuelle du lexem
      sort  = LexemSort.get(idSort);
      lex   = LexemVariableName.get(idVar);
      if(lex==null) {
         lex = new LexemVariableName(idVar, "var"+idVar);
         lex.put();
      }
      symbol=SymbolExtensionVariable.getCreate(idVar,sort);
      if (true) return new Term(symbol,subterms);
          break;
        default:
          jj_expLA1[48] = jj_gen;
          switch (nextToken.kind) {
          case 34:
            jj_consume_token(34);
            intValue = readInt();
            jj_consume_token(24);
      symbol = SymbolInteger.get(intValue);
      if(symbol == null) {
         symbol = new SymbolInteger(intValue, LexemSort.sortInteger);
         symbol.put();
      }
      if (true) return new Term(symbol,subterms);
            break;
          default:
            jj_expLA1[47] = jj_gen;
            switch (nextToken.kind) {
            case 35:
              jj_consume_token(35);
              intValue = readInt();
              jj_consume_token(24);
      symbol = SymbolIdentifier.get(intValue);
      if(symbol == null) {
         symbol = new SymbolIdentifier(intValue, LexemSort.sortIdentifier);
         symbol.put();
      }
      if (true) return new Term(symbol,subterms);
              break;
            default:
              jj_expLA1[46] = jj_gen;
              switch (nextToken.kind) {
              case 36:
                jj_consume_token(36);
                stringValue = ElanString();
                jj_consume_token(24);
      symbol = SymbolString.get(stringValue);
      if(symbol == null) {
         symbol = new SymbolString(stringValue, LexemSort.sortString);
         symbol.put();
      }
      if (true) return new Term(symbol,subterms);
                break;
              default:
                jj_expLA1[45] = jj_gen;
                jj_consume_token(-1);
                throw new ParseException();
              }
            }
          }
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  static final boolean[] jj_mask_45 = new boolean[58];
  static {
    jj_mask_45[36] = true;
  }
  static final boolean[] jj_mask_46 = new boolean[58];
  static {
    jj_mask_46[35] = true;
  }
  static final boolean[] jj_mask_47 = new boolean[58];
  static {
    jj_mask_47[34] = true;
  }
  static final boolean[] jj_mask_48 = new boolean[58];
  static {
    jj_mask_48[33] = true;
  }
  static final boolean[] jj_mask_49 = new boolean[58];
  static {
    jj_mask_49[32] = true;
  }
  static final boolean[] jj_mask_50 = new boolean[58];
  static {
    jj_mask_50[31] = true;
  }
  
  static final public String ElanString() throws ParseException {
  String stringValue = new String();
  int code;
    label_11:
    while (true) {
      switch (nextToken.kind) {
      case INTEGER:
      case 20:
        ;
        break;
      default:
        jj_expLA1[51] = jj_gen;
        break label_11;
      }
      code = readInt();
      jj_consume_token(DOT);
      stringValue+= (new Character((char)code)).toString();
    }
    jj_consume_token(NIL);
    if (true) return "\"" + stringValue + "\"";
    throw new Error("Missing return statement in function");
  }

  static final boolean[] jj_mask_51 = new boolean[58];
  static {
    jj_mask_51[INTEGER] =
    jj_mask_51[20] = true;
  }
  
  static final public Vector ElanTerms() throws ParseException {
  Vector subterms = new Vector(2);
  Term t;
    label_12:
    while (true) {
      switch (nextToken.kind) {
      case 31:
      case 32:
      case 33:
      case 34:
      case 35:
      case 36:
        ;
        break;
      default:
        jj_expLA1[52] = jj_gen;
        break label_12;
      }
      t = BuildElanTerm();
      subterms.addElement(t);
      jj_consume_token(DOT);
    }
    jj_consume_token(NIL);
         if (true) return subterms;
    throw new Error("Missing return statement in function");
  }

  static final boolean[] jj_mask_52 = new boolean[58];
  static {
    jj_mask_52[31] =
    jj_mask_52[32] =
    jj_mask_52[33] =
    jj_mask_52[34] =
    jj_mask_52[35] =
    jj_mask_52[36] = true;
  }
  
  static final public BranchEvaluation Wheres(LineariseCondition linearConditions) throws ParseException {
  LocalEvaluation locEval;
  Vector list = new Vector(2);
  int max;
    label_13:
    while (true) {
      switch (nextToken.kind) {
      case 37:
      case 38:
      case 39:
      case 40:
        ;
        break;
      default:
        jj_expLA1[53] = jj_gen;
        break label_13;
      }
      switch (nextToken.kind) {
      case 37:
        locEval = Condition();
       list.addElement(locEval);
        break;
      default:
        jj_expLA1[56] = jj_gen;
        switch (nextToken.kind) {
        case 40:
          locEval = Choice(linearConditions);
       list.addElement(locEval);
          break;
        default:
          jj_expLA1[55] = jj_gen;
          switch (nextToken.kind) {
          case 38:
          case 39:
            locEval = LocalAffectation();
       ((LocalAffectation)locEval).linearise(linearConditions);
       list.addElement(locEval);
       if(Flags.debug && linearConditions.getConditions().size()>0) {
         System.out.println("linearise locEval: " + locEval);
       }

       for(int i=0 ; i<linearConditions.getConditions().size() ; i++) {
         list.addElement(linearConditions.conditionAt(i));
       }
       linearConditions.removeAllConditions();
            break;
          default:
            jj_expLA1[54] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
      jj_consume_token(DOT);
    }
    jj_consume_token(NIL);
       if (true) return new BranchEvaluation(list);
    throw new Error("Missing return statement in function");
  }

  static final boolean[] jj_mask_53 = new boolean[58];
  static {
    jj_mask_53[37] =
    jj_mask_53[38] =
    jj_mask_53[39] =
    jj_mask_53[40] = true;
  }
  static final boolean[] jj_mask_54 = new boolean[58];
  static {
    jj_mask_54[38] =
    jj_mask_54[39] = true;
  }
  static final boolean[] jj_mask_55 = new boolean[58];
  static {
    jj_mask_55[40] = true;
  }
  static final boolean[] jj_mask_56 = new boolean[58];
  static {
    jj_mask_56[37] = true;
  }
  
  static final public Condition Condition() throws ParseException {
  Term term;
  Condition cond;
    jj_consume_token(37);
    term = ElanTerm();
    jj_consume_token(24);
      cond = new Condition(term);
      if (true) return cond;
    throw new Error("Missing return statement in function");
  }

  static final public LocalAffectation LocalAffectation() throws ParseException {
  Term leftside;
  Term rightside;
  Lexem strategyName=null;
  LocalAffectation where;
  int stratNameIndex;
  int intSort;
    switch (nextToken.kind) {
    case 38:
      jj_consume_token(38);
      leftside = ElanTerm();
      jj_consume_token(COMMA);
      stratNameIndex = readInt();
      jj_consume_token(COMMA);
      rightside = ElanTerm();
      jj_consume_token(24);
      if( stratNameIndex != -1 ) {
         strategyName = LexemStrategyName.get(stratNameIndex);
      }
      where = new LocalAffectation(leftside,strategyName,rightside);
      if (true) return where;
      break;
    default:
      jj_expLA1[58] = jj_gen;
      switch (nextToken.kind) {
      case 39:
        jj_consume_token(39);
        leftside = ElanTerm();
        jj_consume_token(COMMA);
        intSort = readInt();
        jj_consume_token(COMMA);
        stratNameIndex = readInt();
        jj_consume_token(COMMA);
        rightside = ElanTerm();
        jj_consume_token(24);
      if( stratNameIndex != -1 ) {
         strategyName = LexemStrategyName.get(stratNameIndex);
      }
      where = new LocalAffectation(leftside,strategyName,rightside);
      if (true) return where;
        break;
      default:
        jj_expLA1[57] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  static final boolean[] jj_mask_57 = new boolean[58];
  static {
    jj_mask_57[39] = true;
  }
  static final boolean[] jj_mask_58 = new boolean[58];
  static {
    jj_mask_58[38] = true;
  }
  
  static final public Choice Choice(LineariseCondition linearConditions) throws ParseException {
  Choice choice;
  Vector list = new Vector();
  BranchEvaluation branch;
    jj_consume_token(40);
    label_14:
    while (true) {
      if (jj_2_1(2)) {
        ;
      } else {
        break label_14;
      }
      branch = Wheres(linearConditions);
      jj_consume_token(DOT);
         list.addElement(branch);
    }
    jj_consume_token(NIL);
    jj_consume_token(24);
      choice = new Choice(list);
      if (true) return choice;
    throw new Error("Missing return statement in function");
  }

  static final public void StrategyDeclaration() throws ParseException {
  Strategy strat;
  Lexem stratName;
  int intModule;
  StrategyTerm rightside;
  int id;
  int idSort;
  Lexem sort;
    label_15:
    while (true) {
      switch (nextToken.kind) {
      case 41:
        ;
        break;
      default:
        jj_expLA1[59] = jj_gen;
        break label_15;
      }
      jj_consume_token(41);
      id = readInt();
      jj_consume_token(COMMA);
      idSort = readInt();
      jj_consume_token(COMMA);
      intModule = readInt();
      jj_consume_token(COMMA);
      rightside = StrategyBody();
      jj_consume_token(24);
      switch (nextToken.kind) {
      case END:
        jj_consume_token(END);
        break;
      default:
        jj_expLA1[61] = jj_gen;
        switch (nextToken.kind) {
        case DOT:
          jj_consume_token(DOT);
          break;
        default:
          jj_expLA1[60] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
     if(!Flags.quiet && !Flags.debug) {
       //System.out.print(".");
     }
     stratName = LexemStrategyName.get(id);
     sort = LexemSort.get(idSort);
     strat = new Strategy(stratName,sort,rightside);
     Strategy.addElement(strat);
    }
    jj_consume_token(ENDDEF);
  }

  static final boolean[] jj_mask_59 = new boolean[58];
  static {
    jj_mask_59[41] = true;
  }
  static final boolean[] jj_mask_60 = new boolean[58];
  static {
    jj_mask_60[DOT] = true;
  }
  static final boolean[] jj_mask_61 = new boolean[58];
  static {
    jj_mask_61[END] = true;
  }
  
  static final public StrategyTerm StrategyBody() throws ParseException {
  StrategyTerm head;
  StrategyTerm tail=null;
  Vector subterms = new Vector(2);
    head = StrategyTerm();
      subterms.addElement(head);
    label_16:
    while (true) {
      switch (nextToken.kind) {
      case 42:
        ;
        break;
      default:
        jj_expLA1[62] = jj_gen;
        break label_16;
      }
      jj_consume_token(42);
      tail = StrategyTerm();
      subterms.addElement(tail);
    }
      if(subterms.size() <= 1) {
         if (true) return head;
      } else {
         if (true) return new StrategyCons(subterms);
      }
    throw new Error("Missing return statement in function");
  }

  static final boolean[] jj_mask_62 = new boolean[58];
  static {
    jj_mask_62[42] = true;
  }
  
  static final public StrategyTerm StrategyTerm() throws ParseException {
  Vector subterms;
  StrategyTerm stratBody;
  StrategyTerm stratTerm;
  Lexem stratName;
  int id;
    switch (nextToken.kind) {
    case 43:
      jj_consume_token(43);
      if (true) return new StrategyId();
      break;
    default:
      jj_expLA1[74] = jj_gen;
      switch (nextToken.kind) {
      case 44:
        jj_consume_token(44);
      if (true) return new StrategyFail();
        break;
      default:
        jj_expLA1[73] = jj_gen;
        switch (nextToken.kind) {
        case 45:
          jj_consume_token(45);
      if (true) return new StrategyMeta();
          break;
        default:
          jj_expLA1[72] = jj_gen;
          switch (nextToken.kind) {
          case 46:
            jj_consume_token(46);
            subterms = RuleNames();
            jj_consume_token(24);
      if (true) return new StrategyOneRule(subterms);
            break;
          default:
            jj_expLA1[71] = jj_gen;
            switch (nextToken.kind) {
            case 47:
              jj_consume_token(47);
              subterms = RuleNames();
              jj_consume_token(24);
      if (true) return new StrategyDcRule(subterms);
              break;
            default:
              jj_expLA1[70] = jj_gen;
              switch (nextToken.kind) {
              case 48:
                jj_consume_token(48);
                subterms = RuleNames();
                jj_consume_token(24);
      if (true) return new StrategyDkRule(subterms);
                break;
              default:
                jj_expLA1[69] = jj_gen;
                switch (nextToken.kind) {
                case 49:
                  jj_consume_token(49);
                  subterms = StrategyTerms();
                  jj_consume_token(24);
      if (true) return new StrategyOneStrat(subterms);
                  break;
                default:
                  jj_expLA1[68] = jj_gen;
                  switch (nextToken.kind) {
                  case 50:
                    jj_consume_token(50);
                    subterms = StrategyTerms();
                    jj_consume_token(24);
      if (true) return new StrategyDcStrat(subterms);
                    break;
                  default:
                    jj_expLA1[67] = jj_gen;
                    switch (nextToken.kind) {
                    case 51:
                      jj_consume_token(51);
                      subterms = StrategyTerms();
                      jj_consume_token(24);
      if (true) return new StrategyDkStrat(subterms);
                      break;
                    default:
                      jj_expLA1[66] = jj_gen;
                      switch (nextToken.kind) {
                      case 52:
                        jj_consume_token(52);
                        stratBody = StrategyBody();
                        jj_consume_token(24);
      subterms = new Vector(1);
      subterms.addElement(stratBody);
      if (true) return new StrategyRepeat(subterms);
                        break;
                      default:
                        jj_expLA1[65] = jj_gen;
                        switch (nextToken.kind) {
                        case 53:
                          jj_consume_token(53);
                          stratBody = StrategyBody();
                          jj_consume_token(24);
      subterms = new Vector(1);
      subterms.addElement(stratBody);
      if (true) return new StrategyIterate(subterms);
                          break;
                        default:
                          jj_expLA1[64] = jj_gen;
                          switch (nextToken.kind) {
                          case 54:
                            jj_consume_token(54);
                            stratName = StrategyName();
                            jj_consume_token(24);
      if (true) return new StrategyCall(stratName);
                            break;
                          default:
                            jj_expLA1[63] = jj_gen;
                            jj_consume_token(-1);
                            throw new ParseException();
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  static final boolean[] jj_mask_63 = new boolean[58];
  static {
    jj_mask_63[54] = true;
  }
  static final boolean[] jj_mask_64 = new boolean[58];
  static {
    jj_mask_64[53] = true;
  }
  static final boolean[] jj_mask_65 = new boolean[58];
  static {
    jj_mask_65[52] = true;
  }
  static final boolean[] jj_mask_66 = new boolean[58];
  static {
    jj_mask_66[51] = true;
  }
  static final boolean[] jj_mask_67 = new boolean[58];
  static {
    jj_mask_67[50] = true;
  }
  static final boolean[] jj_mask_68 = new boolean[58];
  static {
    jj_mask_68[49] = true;
  }
  static final boolean[] jj_mask_69 = new boolean[58];
  static {
    jj_mask_69[48] = true;
  }
  static final boolean[] jj_mask_70 = new boolean[58];
  static {
    jj_mask_70[47] = true;
  }
  static final boolean[] jj_mask_71 = new boolean[58];
  static {
    jj_mask_71[46] = true;
  }
  static final boolean[] jj_mask_72 = new boolean[58];
  static {
    jj_mask_72[45] = true;
  }
  static final boolean[] jj_mask_73 = new boolean[58];
  static {
    jj_mask_73[44] = true;
  }
  static final boolean[] jj_mask_74 = new boolean[58];
  static {
    jj_mask_74[43] = true;
  }
  
  static final public Lexem StrategyName() throws ParseException {
  Lexem name;
  int id;
    id = readInt();
      name = LexemStrategyName.get(id);
      if(name == null) {
         if (true) throw new InternalError("strategyName sym" + id + " not found");
      }
      if (true) return name;
    throw new Error("Missing return statement in function");
  }

  static final public StrategyTerm RuleName() throws ParseException {
  Lexem name;
  int id;
    id = readInt();
      name = LexemRuleName.get(id);
      if(name == null) {
         if (true) throw new InternalError("ruleName sym" + id + " not found");
      }
      if (true) return new StrategyRuleName(name);
    throw new Error("Missing return statement in function");
  }

  static final public Vector RuleNames() throws ParseException {
  Vector subterms = new Vector(3);
  StrategyTerm t;
    t = RuleName();
      subterms.addElement(t);
    switch (nextToken.kind) {
    case DOT:
      jj_consume_token(DOT);
      label_17:
      while (true) {
        switch (nextToken.kind) {
        case INTEGER:
        case 20:
          ;
          break;
        default:
          jj_expLA1[75] = jj_gen;
          break label_17;
        }
        t = RuleName();
        jj_consume_token(DOT);
      subterms.addElement(t);
      }
      jj_consume_token(NIL);
      break;
    default:
      jj_expLA1[76] = jj_gen;
      ;
    }
      if (true) return subterms;
    throw new Error("Missing return statement in function");
  }

  static final boolean[] jj_mask_75 = new boolean[58];
  static {
    jj_mask_75[INTEGER] =
    jj_mask_75[20] = true;
  }
  static final boolean[] jj_mask_76 = new boolean[58];
  static {
    jj_mask_76[DOT] = true;
  }
  
  static final public Vector StrategyTerms() throws ParseException {
  Vector subterms = new Vector(3);
  StrategyTerm t;
    t = StrategyBody();
      subterms.addElement(t);
    switch (nextToken.kind) {
    case COMMA:
      label_18:
      while (true) {
        jj_consume_token(COMMA);
        t = StrategyBody();
      subterms.addElement(t);
        switch (nextToken.kind) {
        case COMMA:
          ;
          break;
        default:
          jj_expLA1[77] = jj_gen;
          break label_18;
        }
      }
      break;
    default:
      jj_expLA1[78] = jj_gen;
      ;
    }
      if (true) return subterms;
    throw new Error("Missing return statement in function");
  }

  static final boolean[] jj_mask_77 = new boolean[58];
  static {
    jj_mask_77[COMMA] = true;
  }
  static final boolean[] jj_mask_78 = new boolean[58];
  static {
    jj_mask_78[COMMA] = true;
  }
  
  static final public Query QueryDeclaration() throws ParseException {
  int intSourceSort;
  int intResultSort;
  Term startWith;
  Term checkWith;
  int stratNameIndex;
  Lexem strategyName=null;
  int id;
    jj_consume_token(55);
    intSourceSort = readInt();
    jj_consume_token(COMMA);
    intResultSort = readInt();
    jj_consume_token(COMMA);
    stratNameIndex = readInt();
    jj_consume_token(COMMA);
    startWith = ElanTerm();
    jj_consume_token(COMMA);
    checkWith = ElanTerm();
    jj_consume_token(24);
     if( stratNameIndex != -1 ) {
         strategyName = LexemStrategyName.get(stratNameIndex);
     }
     if (true) return new Query(intSourceSort,strategyName,startWith);
    throw new Error("Missing return statement in function");
  }

// Old switch
  static final public RightHandSide ElanRightHandSide(LineariseCondition LinearConditions) throws ParseException {
  Term rightside;
  BranchEvaluation wheres;
  Vector caseTerm,caseRhs;
    switch (nextToken.kind) {
    case 56:
      jj_consume_token(56);
      wheres = Wheres(LinearConditions);
      jj_consume_token(COMMA);
      rightside = ElanTerm();
      jj_consume_token(24);
      if (true) return new RhsNoSwitchTerm(rightside,wheres);
      break;
    default:
      jj_expLA1[80] = jj_gen;
      switch (nextToken.kind) {
      case 57:
        jj_consume_token(57);
      caseTerm=new Vector();
      caseRhs=new Vector();
        wheres = Wheres(LinearConditions);
        jj_consume_token(COMMA);
        SwitchBranchs(caseTerm,caseRhs,LinearConditions);
        jj_consume_token(24);
      if (true) return new RhsSwitchTerm(caseTerm,caseRhs,wheres);
        break;
      default:
        jj_expLA1[79] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  static final boolean[] jj_mask_79 = new boolean[58];
  static {
    jj_mask_79[57] = true;
  }
  static final boolean[] jj_mask_80 = new boolean[58];
  static {
    jj_mask_80[56] = true;
  }
  
  static final public void SwitchBranchs(Vector caseList, Vector caseRhs,
                   LineariseCondition LinearConditions) throws ParseException {
  Term caseTerm;
  RightHandSide rightside;
    label_19:
    while (true) {
      switch (nextToken.kind) {
      case 31:
      case 32:
      case 33:
      case 34:
      case 35:
      case 36:
        ;
        break;
      default:
        jj_expLA1[81] = jj_gen;
        break label_19;
      }
      caseTerm = ElanTerm();
      jj_consume_token(COMMA);
      rightside = ElanRightHandSide(LinearConditions);
      caseList.addElement(caseTerm);
      caseRhs.addElement(rightside);
      jj_consume_token(DOT);
    }
    jj_consume_token(NIL);
  }

  static final boolean[] jj_mask_81 = new boolean[58];
  static {
    jj_mask_81[31] =
    jj_mask_81[32] =
    jj_mask_81[33] =
    jj_mask_81[34] =
    jj_mask_81[35] =
    jj_mask_81[36] = true;
  }
  
  static final private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_1();
    jj_save(0, xla);
    return retval;
  }

  static final private boolean jj_3R_22() {
    if (jj_3R_25()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_21() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_20() {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_21()) { jj_scanpos = xsp; break; }
      if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    }
    if (jj_scan_token(NIL)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_33() {
    if (jj_scan_token(32)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_1() {
    if (jj_3R_20()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_scan_token(DOT)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_32() {
    if (jj_scan_token(31)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_31() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_26() {
    if (jj_scan_token(40)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_1()) { jj_scanpos = xsp; break; }
      if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    }
    if (jj_scan_token(NIL)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_30() {
    if (jj_scan_token(39)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_28()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_29() {
    if (jj_scan_token(38)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_28()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_28() {
    if (jj_3R_31()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_27() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_37() {
    if (jj_scan_token(36)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_25() {
    if (jj_scan_token(37)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_28()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_36() {
    if (jj_scan_token(35)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_35() {
    if (jj_scan_token(34)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_34() {
    if (jj_scan_token(33)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_24() {
    if (jj_3R_27()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_23() {
    if (jj_3R_26()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static private boolean jj_initialized_once = false;
  static public REFParserTokenManager token_source;
  static ASCII_CharStream jj_input_stream;
  static public Token token, nextToken;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static public boolean lookingAhead = false;
  static private boolean jj_semLA;
  static private int jj_gen;
  static private int[] jj_expLA1 = new int[82];
  static private JJREFParserCalls[] jj_2_rtns = new JJREFParserCalls[1];
  static private boolean jj_rescan = false;

  public REFParser(java.io.InputStream stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new ASCII_CharStream(stream, 1, 1);
    token_source = new REFParserTokenManager(jj_input_stream);
    token = new Token();
    token.next = nextToken = token_source.getNextToken();
    jj_gen = 0;
    for (int i = 0; i < 82; i++) jj_expLA1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJREFParserCalls();
  }

  static public void ReInit(java.io.InputStream stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    token.next = nextToken = token_source.getNextToken();
    jj_gen = 0;
    for (int i = 0; i < 82; i++) jj_expLA1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJREFParserCalls();
  }

  public REFParser(REFParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    token.next = nextToken = token_source.getNextToken();
    jj_gen = 0;
    for (int i = 0; i < 82; i++) jj_expLA1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJREFParserCalls();
  }

  public void ReInit(REFParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    token.next = nextToken = token_source.getNextToken();
    jj_gen = 0;
    for (int i = 0; i < 82; i++) jj_expLA1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJREFParserCalls();
  }

  static final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken = token;
    if ((token = nextToken).next != null) nextToken = nextToken.next;
    else nextToken = nextToken.next = token_source.getNextToken();
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    nextToken = token;
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static final private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    return (jj_scanpos.kind != kind);
  }

  static final public Token getNextToken() {
    if ((token = nextToken).next != null) nextToken = nextToken.next;
    else nextToken = nextToken.next = token_source.getNextToken();
    jj_gen++;
    return token;
  }

  static final public Token getToken(int index) {
    Token t = lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private java.util.Vector jj_expentries = new java.util.Vector();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Enumeration enum = jj_expentries.elements(); enum.hasMoreElements();) {
        int[] oldentry = (int[])(enum.nextElement());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
        }
      }
      if (!exists) jj_expentries.addElement(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  static final public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[58];
    boolean[] mask = null;
    for (int i = 0; i < 58; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 82; i++) {
      if (jj_expLA1[i] == jj_gen) {
        switch (i) {
          case 0: mask = jj_mask_0; break;
          case 1: mask = jj_mask_1; break;
          case 2: mask = jj_mask_2; break;
          case 3: mask = jj_mask_3; break;
          case 4: mask = jj_mask_4; break;
          case 5: mask = jj_mask_5; break;
          case 6: mask = jj_mask_6; break;
          case 7: mask = jj_mask_7; break;
          case 8: mask = jj_mask_8; break;
          case 9: mask = jj_mask_9; break;
          case 10: mask = jj_mask_10; break;
          case 11: mask = jj_mask_11; break;
          case 12: mask = jj_mask_12; break;
          case 13: mask = jj_mask_13; break;
          case 14: mask = jj_mask_14; break;
          case 15: mask = jj_mask_15; break;
          case 16: mask = jj_mask_16; break;
          case 17: mask = jj_mask_17; break;
          case 18: mask = jj_mask_18; break;
          case 19: mask = jj_mask_19; break;
          case 20: mask = jj_mask_20; break;
          case 21: mask = jj_mask_21; break;
          case 22: mask = jj_mask_22; break;
          case 23: mask = jj_mask_23; break;
          case 24: mask = jj_mask_24; break;
          case 25: mask = jj_mask_25; break;
          case 26: mask = jj_mask_26; break;
          case 27: mask = jj_mask_27; break;
          case 28: mask = jj_mask_28; break;
          case 29: mask = jj_mask_29; break;
          case 30: mask = jj_mask_30; break;
          case 31: mask = jj_mask_31; break;
          case 32: mask = jj_mask_32; break;
          case 33: mask = jj_mask_33; break;
          case 34: mask = jj_mask_34; break;
          case 35: mask = jj_mask_35; break;
          case 36: mask = jj_mask_36; break;
          case 37: mask = jj_mask_37; break;
          case 38: mask = jj_mask_38; break;
          case 39: mask = jj_mask_39; break;
          case 40: mask = jj_mask_40; break;
          case 41: mask = jj_mask_41; break;
          case 42: mask = jj_mask_42; break;
          case 43: mask = jj_mask_43; break;
          case 44: mask = jj_mask_44; break;
          case 45: mask = jj_mask_45; break;
          case 46: mask = jj_mask_46; break;
          case 47: mask = jj_mask_47; break;
          case 48: mask = jj_mask_48; break;
          case 49: mask = jj_mask_49; break;
          case 50: mask = jj_mask_50; break;
          case 51: mask = jj_mask_51; break;
          case 52: mask = jj_mask_52; break;
          case 53: mask = jj_mask_53; break;
          case 54: mask = jj_mask_54; break;
          case 55: mask = jj_mask_55; break;
          case 56: mask = jj_mask_56; break;
          case 57: mask = jj_mask_57; break;
          case 58: mask = jj_mask_58; break;
          case 59: mask = jj_mask_59; break;
          case 60: mask = jj_mask_60; break;
          case 61: mask = jj_mask_61; break;
          case 62: mask = jj_mask_62; break;
          case 63: mask = jj_mask_63; break;
          case 64: mask = jj_mask_64; break;
          case 65: mask = jj_mask_65; break;
          case 66: mask = jj_mask_66; break;
          case 67: mask = jj_mask_67; break;
          case 68: mask = jj_mask_68; break;
          case 69: mask = jj_mask_69; break;
          case 70: mask = jj_mask_70; break;
          case 71: mask = jj_mask_71; break;
          case 72: mask = jj_mask_72; break;
          case 73: mask = jj_mask_73; break;
          case 74: mask = jj_mask_74; break;
          case 75: mask = jj_mask_75; break;
          case 76: mask = jj_mask_76; break;
          case 77: mask = jj_mask_77; break;
          case 78: mask = jj_mask_78; break;
          case 79: mask = jj_mask_79; break;
          case 80: mask = jj_mask_80; break;
          case 81: mask = jj_mask_81; break;
        }
        for (int j = 0; j < 58; j++) {
          if (mask[j]) la1tokens[j] = true;
        }
      }
    }
    for (int i = 0; i < 58; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  static final public void enable_tracing() {
  }

  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 1; i++) {
      JJREFParserCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
          }
        }
        p = p.next;
      } while (p != null);
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJREFParserCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJREFParserCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

}

class JJREFParserCalls {
  int gen;
  Token first;
  int arg;
  JJREFParserCalls next;
}
