elanlibdir = $(datadir)/elanlib
refdir  = $(elanlibdir)/ref

ELANLIB_REF = \
			Meta_Apply.eln\
			REF.eln\
			divers2string.eln\
			ref2string.eln\
			ref2term.eln\
			ref_idents.eln\
			ref_modules.eln\
			ref_read.eln\
			ref_rules.eln\
			ref_sorts.eln\
			ref_strategies.eln\
			ref_tables.eln\
			ref_terms.eln\
			ref_unify.eln\
			ref_unify_builtin.eln\
			ref_write.eln\
			refstring2string.eln\
			string2refterm.eln

EXTRA_DIST  = $(ELANLIB_REF)
ref_DATA = $(ELANLIB_REF)

