/* Generated By:JavaCC: Do not edit this line. REFParser.java */
package rem.parser;
  import java.util.*;
  import rem.compiler.*;
  import rem.exception.*;

public class REFParser implements REFParserConstants {

/*
TOKEN : {
 <IDENTIFIER: <LETTER> (<LETTER> | <DIGIT>)*>
|  <#LETTER: ["$","A"-"Z","_","a"-"z"]>
|  <#DIGIT: ["0"-"9"]>
}
*/
  static final public int readInt() throws ParseException {
  boolean negative = false;
  Token token;
  int res;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 20:
      jj_consume_token(20);
        negative=true;
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    token = jj_consume_token(INTEGER);
    res = Integer.parseInt(token.image);
    if(negative)
    res = -res;
    {if (true) return res;}
    throw new Error("Missing return statement in function");
  }

  static final public Query Start(OutputCode s) throws ParseException {
  Query query;
  int numberOfGrammarRule = 0;
    jj_consume_token(LEXEM_DECLARATION);
    LexemIdentifierDeclaration();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case END:
      jj_consume_token(END);
      break;
    case COMMA:
      jj_consume_token(COMMA);
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    jj_consume_token(SORT_DECLARATION);
    LexemSortDeclaration();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case END:
      jj_consume_token(END);
      break;
    case COMMA:
      jj_consume_token(COMMA);
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    jj_consume_token(MODULE_DECLARATION);
    LexemModuleDeclaration();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case END:
      jj_consume_token(END);
      break;
    case COMMA:
      jj_consume_token(COMMA);
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    jj_consume_token(RULENAME_DECLARATION);
    LexemRuleNameDeclaration();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case END:
      jj_consume_token(END);
      break;
    case COMMA:
      jj_consume_token(COMMA);
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    jj_consume_token(STRATEGYNAME_DECLARATION);
    LexemStrategyNameDeclaration();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case END:
      jj_consume_token(END);
      break;
    case COMMA:
      jj_consume_token(COMMA);
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
        // Tables for Earley
      s.write("int gram[] = {\n");
    numberOfGrammarRule = GrammarDeclaration(s,numberOfGrammarRule);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case END:
      jj_consume_token(END);
      break;
    case COMMA:
      jj_consume_token(COMMA);
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    if(!Flags.quiet && !Flags.debug) System.out.print(".");
    numberOfGrammarRule = GrammarDeclaration(s,numberOfGrammarRule);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case END:
      jj_consume_token(END);
      break;
    case COMMA:
      jj_consume_token(COMMA);
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    if(!Flags.quiet && !Flags.debug) System.out.print(".");
    numberOfGrammarRule = GrammarDeclaration(s,numberOfGrammarRule);
    if(!Flags.quiet && !Flags.debug) System.out.print(".");
      // Tables for Earley
    s.write("0};\n");
    s.write("int pos = " + numberOfGrammarRule + ";\n");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case END:
      jj_consume_token(END);
      break;
    case COMMA:
      jj_consume_token(COMMA);
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    RuleDeclaration();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case END:
      jj_consume_token(END);
      break;
    case COMMA:
      jj_consume_token(COMMA);
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    StrategyDeclaration();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case END:
      jj_consume_token(END);
      break;
    case COMMA:
      jj_consume_token(COMMA);
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      if(!Flags.quiet && !Flags.debug) System.out.print(".");
    query = QueryDeclaration();
    if(!Flags.quiet && !Flags.debug) System.out.print(".");
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case END:
      jj_consume_token(END);
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    jj_consume_token(0);
      if(!Flags.quiet && !Flags.debug) System.out.println("");
    {if (true) return query;}
    throw new Error("Missing return statement in function");
  }

  static final public void LexemIdentifierDeclaration() throws ParseException {
  Token tokenId;
  int id;
  String lexName;
  Lexem lex;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER:
      case 20:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_1;
      }
      id = readInt();
      jj_consume_token(21);
      tokenId = jj_consume_token(STRING_LITERAL);
      jj_consume_token(DOT);
      lexName = tokenId.image.substring(1,tokenId.image.length()-1);
      lex = new LexemIdentifier( id, lexName );
      lex.put();
    }
    jj_consume_token(NIL);
  }

  static final public void LexemSortDeclaration() throws ParseException {
  Token tokenId;
  int id;
  String lexName;
  Lexem lex;
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER:
      case 20:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_2;
      }
      id = readInt();
      jj_consume_token(21);
      tokenId = jj_consume_token(STRING_LITERAL);
      jj_consume_token(DOT);
      lexName = tokenId.image.substring(1,tokenId.image.length()-1);
      lex = new LexemSort( id, lexName );
      lex.put();
    }
    jj_consume_token(NIL);
  }

  static final public void LexemModuleDeclaration() throws ParseException {
  Token tokenId;
  int id;
  String lexName;
  Lexem lex;
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER:
      case 20:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_3;
      }
      id = readInt();
      jj_consume_token(21);
      tokenId = jj_consume_token(STRING_LITERAL);
      jj_consume_token(DOT);
      lexName = tokenId.image.substring(1,tokenId.image.length()-1);
      lex = new LexemModule( id, lexName );
      lex.put();
    }
    jj_consume_token(NIL);
  }

  static final public void LexemRuleNameDeclaration() throws ParseException {
  Token tokenId;
  int id;
  String lexName;
  Lexem lex;
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER:
      case 20:
        ;
        break;
      default:
        jj_la1[15] = jj_gen;
        break label_4;
      }
      id = readInt();
      jj_consume_token(21);
      tokenId = jj_consume_token(STRING_LITERAL);
      jj_consume_token(DOT);
      lexName = tokenId.image.substring(1,tokenId.image.length()-1);
      lex = new LexemRuleName( id, lexName );
      lex.put();
    }
    jj_consume_token(NIL);
  }

  static final public void LexemStrategyNameDeclaration() throws ParseException {
  Token tokenId;
  int id;
  String lexName;
  Lexem lex;
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER:
      case 20:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_5;
      }
      id = readInt();
      jj_consume_token(21);
      tokenId = jj_consume_token(STRING_LITERAL);
      jj_consume_token(DOT);
      lexName = tokenId.image.substring(1,tokenId.image.length()-1);
      lex = new LexemStrategyName( id, lexName );
      lex.put();
    }
    jj_consume_token(NIL);
  }

  static final public int GrammarDeclaration(OutputCode s,int numberOfGrammarRule) throws ParseException {
  int idSort;
  int isBuiltin;
  LexemSort lexSort;
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 22:
        ;
        break;
      default:
        jj_la1[17] = jj_gen;
        break label_6;
      }
      jj_consume_token(22);
      idSort = readInt();
      jj_consume_token(21);
      isBuiltin = readInt();
      jj_consume_token(21);
      lexSort = LexemSort.get(idSort);
      if(isBuiltin==1) {
        lexSort.setBuiltin();
      }
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INTEGER:
        case 20:
          ;
          break;
        default:
          jj_la1[18] = jj_gen;
          break label_7;
        }
        numberOfGrammarRule = SymbolDeclaration(lexSort,s,numberOfGrammarRule);
        jj_consume_token(DOT);
      }
      jj_consume_token(NIL);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case END:
        jj_consume_token(END);
        break;
      case DOT:
        jj_consume_token(DOT);
        break;
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(ENDDEF);
      {if (true) return numberOfGrammarRule;}
    throw new Error("Missing return statement in function");
  }

  static final public int SymbolDeclaration(Lexem lexSort, OutputCode s,int numberOfGrammarRule) throws ParseException {
  int intGrammar;
  int intSym;
  int intArity;
  int intInfo;
  int intSemantic;
  int intStrategy;
  int intTheory;
  int intLocStrat;

  Symbol sym;
  Lexem lexem;
  Vector vectorLex = new Vector(10);
  Lexem[] arrayLex;
    // for Earley tables
  int i,type;
  int vectorLexSize = 0;
    intGrammar = readInt();
    jj_consume_token(21);
    // unused
        intSym = readInt();
    jj_consume_token(21);
    intArity = readInt();
    jj_consume_token(21);
    // unused
        intInfo = readInt();
    jj_consume_token(21);
    // unused
        intSemantic = readInt();
    jj_consume_token(21);
    intTheory = readInt();
    jj_consume_token(21);
    intStrategy = readInt();
    jj_consume_token(21);
    label_8:
    while (true) {
      lexem = ALexem();
      jj_consume_token(DOT);
        vectorLex.addElement(lexem);
        if (lexem != LexemIdentifier.blank) {
          vectorLexSize++;
        }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 23:
      case 25:
      case 26:
      case 27:
      case 28:
        ;
        break;
      default:
        jj_la1[20] = jj_gen;
        break label_8;
      }
    }
    jj_consume_token(NIL);
    jj_consume_token(21);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER:
      case 20:
        ;
        break;
      default:
        jj_la1[21] = jj_gen;
        break label_9;
      }
      intLocStrat = readInt();
      jj_consume_token(DOT);

    }
    jj_consume_token(NIL);
    arrayLex = new Lexem[vectorLex.size()];
    vectorLex.copyInto(arrayLex);
    vectorLex.removeAllElements();

      /*
       * Generation des tableaux pour Earley
       */
      // Global Rule
    s.write("1,");
    int info = intArity+(intInfo*(007777+1));
    s.write(info + ",");
    s.write(intSym + ",");
    s.write(lexSort.getCode() + ",");
    s.write(vectorLexSize + ",");

    numberOfGrammarRule += 5;
    for(i=0 ; i<arrayLex.length ; i++) {
      lexem = (Lexem)arrayLex[i];
      if(lexem != LexemIdentifier.blank) {
          // Type
        if(lexem instanceof LexemIdentifier) type = 0;
        else if(lexem instanceof LexemSort) type = 1;
        else if(lexem instanceof LexemChar) type = 2;
        else if(lexem instanceof LexemNum) type = 3;
        else    {if (true) throw new InternalError("Wrong lexem in REF file");}
        s.write(type + ",");
        s.write(lexem.getCode() + ",");
        numberOfGrammarRule += 2;
      }
    }
    s.write("\n");

    if(Flags.strat > 0 && intStrategy != 0) {   // Peter
      if (ElanConstants.isFsym(intStrategy)) {
        sym = new SymbolFsym(intSym,arrayLex,lexSort,intSemantic,intStrategy);
        sym.put(); }
      else if (ElanConstants.isLab(intStrategy)) {
        sym = new SymbolLab(intSym,arrayLex,lexSort,intSemantic,intStrategy);
        sym.put(); }
      else if (ElanConstants.isApply(intStrategy)) {
        sym = new SymbolApply(intSym,arrayLex,lexSort,intSemantic,intStrategy);
        sym.put(); }
      else { // if (ElanConstants.isDstr(intStrategy))
        sym = new SymbolDstr(intSym,arrayLex,lexSort,intSemantic,intStrategy);
        sym.put(); }                                    // Peter
    } else if( intSemantic != 0 ) {
      sym = new SymbolBuiltin(intSym,arrayLex,lexSort,intSemantic,intTheory);
      sym.put();
      if(intSemantic<0 && Symbol.get(-intSemantic)==null) {
        sym = new SymbolBuiltin(-intSemantic,arrayLex,lexSort,-intSemantic,intTheory);
        sym.put();
      }
    } else if( intTheory == 0 ) {
      sym = new SymbolFree(intSym,arrayLex,lexSort);
      sym.put();
    } else if( intTheory == 2 ) {
      sym = new SymbolAC(intSym,arrayLex,lexSort);
      sym.put();
    }
    {if (true) return numberOfGrammarRule;}
    throw new Error("Missing return statement in function");
  }

  static final public Lexem ALexem() throws ParseException {
  Lexem lex;
  int id;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 23:
      jj_consume_token(23);
      id = readInt();
      jj_consume_token(24);
    {if (true) return LexemIdentifier.get(id);}
      break;
    case 25:
      jj_consume_token(25);
      id = readInt();
      jj_consume_token(24);
      {if (true) return LexemSort.get(id);}
      break;
    case 26:
      jj_consume_token(26);
      id = readInt();
      jj_consume_token(24);
      lex=LexemChar.get(id);
      if(lex==null) {
        lex = new LexemChar(id);
        lex.put();
      }
      {if (true) return lex;}
      break;
    case 27:
      jj_consume_token(27);
      id = readInt();
      jj_consume_token(24);
      lex=LexemNum.get(id);
      if(lex==null) {
        lex = new LexemNum(id);
        lex.put();
      }
      {if (true) return lex;}
      break;
    case 28:
      jj_consume_token(28);
      {if (true) return LexemIdentifier.blank;}
      break;
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public void RuleDeclaration() throws ParseException {
  int intModule;
  int intInfo;
  int intAC;
  int intVarNum;

  Term leftside;
  Term rightside;
  Lexem ruleName=null;
  Lexem ruleSort;
  int idSort;
  RewriteRule rule;
  int id;
  int ruleNameIndex;
  int i;
  List linearConditions;
  BranchEvaluation branch;
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 29:
        ;
        break;
      default:
        jj_la1[23] = jj_gen;
        break label_10;
      }
      jj_consume_token(29);
      ruleNameIndex = readInt();
      jj_consume_token(COMMA);
      if( ruleNameIndex != -1 ) {
        ruleName = LexemRuleName.get(ruleNameIndex);
      } else {
        ruleName = null;
      }
      idSort = readInt();
      jj_consume_token(COMMA);
      ruleSort = LexemSort.get(idSort);
      intModule = readInt();
      jj_consume_token(COMMA);
      intInfo = readInt();
      jj_consume_token(COMMA);
      intAC = readInt();
      jj_consume_token(COMMA);
      // Nombre de variables apparaissant dans la regle
          intVarNum = readInt();
      jj_consume_token(COMMA);
      leftside = unflattenedElanTerm();
      jj_consume_token(COMMA);
      rightside = ElanTerm();
      jj_consume_token(COMMA);
        // calcul de l'ONF
      leftside.flatten();
      leftside.orderedNormalForm();
        // construction de la regle sans wheres
      rule = new RewriteRule(ruleName,
                             ruleSort,
                             leftside,rightside,
                             null,
                             intVarNum);
      if(Flags.debug) {
        System.out.println("Rule:\t" + ruleName + "\n\tlhs = " + leftside);
      }
      // parse et ajoute les wheres
          branch = Wheres(rule);
      rule.setBranch(branch);
      jj_consume_token(24);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case END:
        jj_consume_token(END);
        break;
      case DOT:
        jj_consume_token(DOT);
        break;
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      if(rule.getLeftside().containsExtensionVariable()) {
        if(Flags.debug) {
          System.out.println("extended rules are not compiled:\n" + rule);
        }
      } else {
          // Linearise leftside
        if(Flags.debug) {
          System.out.println("Linearisation");
        }
        linearConditions = leftside.linearise(rule);
          // insertion des conditions en tete
        branch.addAll(0,linearConditions);

        if(Flags.debug && !linearConditions.isEmpty()) {
            //System.out.println("  --> " + leftside);
          System.out.println(rule);
        }

        if(Flags.debug) {
          System.out.println("Transformation phase 2");
        }
        try{
          rule.transformation();
        } catch (RuleTransformed e) {
          System.out.println("Rule Transformed");
        } catch (RuleCompiled e) {
          System.out.println("Rule Compiled");
        } catch (CompileError e) {
          System.out.println("Compile Error");
        }

          /**************************************************
           *** DEBUT DE LA COMPILATION
           **************************************************/
        rule.variableNumbering();

        RewriteRule.addElement(rule);
      }
        /*
      try{
        if(rule.isCompilable()) {
          RewriteRule.addElement(rule);
        } 
      } catch (ACPatternNotCompiled e) {
	if(!Flags.quiet) {
          if(Flags.warnings) {
            System.out.println("\nWarning: " + leftside);
            System.out.println("This pattern is not compiled");
          }
	}
      } catch (ACPatternWithSeveralACSubterms e) {
        System.out.println("\nProblem with pattern: " + leftside);
        System.out.println("\n" + e);
        System.out.println("This pattern cannot be compiled");
        System.out.println("Please, apply a program transformation as described in the manual");
        System.exit(1);
      } catch (CompileError e) {
        System.out.println("\nError with pattern: " + leftside);
        System.out.println("\n" + e);
        System.out.println("This pattern cannot be compiled");
        System.out.println("Please, apply a program transformation as described in the manual");
        System.exit(1);
      }
        */

    }
    jj_consume_token(ENDDEF);
  }

  static final public Term ElanTerm() throws ParseException {
  Term term;
    term = BuildElanTerm();
      //System.out.println("term before flatten = " + term);
    term.flatten();
    term.orderedNormalForm();
    {if (true) return term;}
    throw new Error("Missing return statement in function");
  }

  static final public Term unflattenedElanTerm() throws ParseException {
  Term term;
    term = BuildElanTerm();
    {if (true) return term;}
    throw new Error("Missing return statement in function");
  }

  static final public Term BuildElanTerm() throws ParseException {
  Symbol symbol;
  Lexem lex;
  Lexem sort;
  Vector subterms=null;
  int idFsym;
  int idVar;
  int idSort;
  Object value;
  int intValue;
  String stringValue;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 30:
      jj_consume_token(30);
      subterms = ElanTerms();
      jj_consume_token(COMMA);
      idFsym = readInt();
      jj_consume_token(24);
    symbol=Symbol.get(idFsym);
    if(symbol == null) {
      {if (true) throw new InternalError("symbol sym" + idFsym + " not found");}
    }
    {if (true) return new Term(symbol,subterms);}
      break;
    case 31:
      jj_consume_token(31);
      idVar = readInt();
      jj_consume_token(COMMA);
      idSort = readInt();
      jj_consume_token(24);
      sort = LexemSort.get(idSort);
      symbol=SymbolVariable.getCreate(idVar,sort);
      {if (true) return new Term(symbol,subterms);}
      break;
    case 32:
      jj_consume_token(32);
      idVar = readInt();
      jj_consume_token(COMMA);
      idSort = readInt();
      jj_consume_token(24);
      sort = LexemSort.get(idSort);
      symbol=SymbolExtensionVariable.getCreate(idVar,sort);
      {if (true) return new Term(symbol,subterms);}
      break;
    case 33:
      jj_consume_token(33);
      intValue = readInt();
      jj_consume_token(24);
      symbol = SymbolInteger.get(intValue);
      if(symbol == null) {
        symbol = new SymbolInteger(intValue, LexemSort.sortInteger);
        symbol.put();
      }
      {if (true) return new Term(symbol,subterms);}
      break;
    case 34:
      jj_consume_token(34);
      intValue = readInt();
      jj_consume_token(24);
      symbol = SymbolIdentifier.get(intValue);
      if(symbol == null) {
        symbol = new SymbolIdentifier(intValue, LexemSort.sortIdentifier);
        symbol.put();
      }
      {if (true) return new Term(symbol,subterms);}
      break;
    case 35:
      jj_consume_token(35);
      stringValue = ElanString();
      jj_consume_token(24);
      symbol = SymbolString.get(stringValue);
      if(symbol == null) {
        symbol = new SymbolString(stringValue, LexemSort.sortString);
        symbol.put();
      }
      {if (true) return new Term(symbol,subterms);}
      break;
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public String ElanString() throws ParseException {
  String stringValue = new String();
  int code;
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER:
      case 20:
        ;
        break;
      default:
        jj_la1[26] = jj_gen;
        break label_11;
      }
      code = readInt();
      jj_consume_token(DOT);
      stringValue+= (new Character((char)code)).toString();
    }
    jj_consume_token(NIL);
      {if (true) return "\"" + stringValue + "\"";}
    throw new Error("Missing return statement in function");
  }

  static final public Vector ElanTerms() throws ParseException {
  Vector subterms = new Vector(2);
  Term t;
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 30:
      case 31:
      case 32:
      case 33:
      case 34:
      case 35:
        ;
        break;
      default:
        jj_la1[27] = jj_gen;
        break label_12;
      }
      t = BuildElanTerm();
      subterms.addElement(t);
      jj_consume_token(DOT);
    }
    jj_consume_token(NIL);
      {if (true) return subterms;}
    throw new Error("Missing return statement in function");
  }

  // ajoute les wheres a la regle
  static final public BranchEvaluation Wheres(RewriteRule rule) throws ParseException {
  LocalEvaluation locEval;
  List list = new LinkedList();
  List conditions;
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 36:
      case 37:
      case 38:
      case 39:
        ;
        break;
      default:
        jj_la1[28] = jj_gen;
        break label_13;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 36:
        locEval = Condition();
        list.add(locEval);
        break;
      case 39:
        locEval = Choice(rule);
        list.add(locEval);
        break;
      case 37:
      case 38:
        locEval = LocalAffectation();
        list.add(locEval);
          // linearise locEval et ajoute eventuellement des conditions
        conditions = ((LocalAffectation)locEval).linearise(rule);
        list.addAll(conditions);
        break;
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(DOT);
    }
    jj_consume_token(NIL);
      {if (true) return new BranchEvaluation(list);}
    throw new Error("Missing return statement in function");
  }

  static final public Condition Condition() throws ParseException {
  Term term;
    jj_consume_token(36);
    term = ElanTerm();
    jj_consume_token(24);
    {if (true) return new Condition(term);}
    throw new Error("Missing return statement in function");
  }

  static final public LocalAffectation LocalAffectation() throws ParseException {
  Term leftside;
  Term rightside;
  Lexem strategyName=null;
  LocalAffectation where;
  int stratNameIndex;
  int intSort;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 37:
      jj_consume_token(37);
      leftside = ElanTerm();
      jj_consume_token(COMMA);
      stratNameIndex = readInt();
      jj_consume_token(COMMA);
      rightside = ElanTerm();
      jj_consume_token(24);
    if( stratNameIndex != -1 ) {
      strategyName = LexemStrategyName.get(stratNameIndex);
    }
    where = new LocalAffectation(leftside,strategyName,rightside);
    {if (true) return where;}
      break;
    case 38:
      jj_consume_token(38);
      leftside = ElanTerm();
      jj_consume_token(COMMA);
      intSort = readInt();
      jj_consume_token(COMMA);
      stratNameIndex = readInt();
      jj_consume_token(COMMA);
      rightside = ElanTerm();
      jj_consume_token(24);
      if( stratNameIndex != -1 ) {
        strategyName = LexemStrategyName.get(stratNameIndex);
      }
      where = new LocalAffectation(leftside,strategyName,rightside);
      {if (true) return where;}
      break;
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public Choice Choice(RewriteRule rule) throws ParseException {
  List list = new ArrayList();
  BranchEvaluation branch;
    jj_consume_token(39);
    label_14:
    while (true) {
      if (jj_2_1(2)) {
        ;
      } else {
        break label_14;
      }
      branch = Wheres(rule);
      jj_consume_token(DOT);
        list.add(branch);
    }
    jj_consume_token(NIL);
    jj_consume_token(24);
      {if (true) return new Choice(list);}
    throw new Error("Missing return statement in function");
  }

  static final public void StrategyDeclaration() throws ParseException {
  Strategy strat;
  Lexem stratName;
  int intModule;
  StrategyTerm rightside;
  int id;
  int idSort;
  Lexem sort;
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 40:
        ;
        break;
      default:
        jj_la1[31] = jj_gen;
        break label_15;
      }
      jj_consume_token(40);
      id = readInt();
      jj_consume_token(COMMA);
      idSort = readInt();
      jj_consume_token(COMMA);
      intModule = readInt();
      jj_consume_token(COMMA);
      rightside = StrategyBody();
      jj_consume_token(24);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case END:
        jj_consume_token(END);
        break;
      case DOT:
        jj_consume_token(DOT);
        break;
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      if(!Flags.quiet && !Flags.debug) {
          //System.out.print(".");
      }
      stratName = LexemStrategyName.get(id);
      sort = LexemSort.get(idSort);
      strat = new Strategy(stratName,sort,rightside);
      Strategy.addElement(strat);
    }
    jj_consume_token(ENDDEF);
  }

  static final public StrategyTerm StrategyBody() throws ParseException {
  StrategyTerm head;
  StrategyTerm tail=null;
  Vector subterms = new Vector(2);
    head = StrategyTerm();
    subterms.addElement(head);
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 41:
        ;
        break;
      default:
        jj_la1[33] = jj_gen;
        break label_16;
      }
      jj_consume_token(41);
      tail = StrategyTerm();
      subterms.addElement(tail);
    }
      if(subterms.size() <= 1) {
        {if (true) return head;}
      } else {
        {if (true) return new StrategyCons(subterms);}
      }
    throw new Error("Missing return statement in function");
  }

  static final public StrategyTerm StrategyTerm() throws ParseException {
  Vector subterms;
  StrategyTerm stratBody;
  StrategyTerm stratTerm;
  Lexem stratName;
  int id;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 42:
      jj_consume_token(42);
      {if (true) return new StrategyId();}
      break;
    case 43:
      jj_consume_token(43);
      {if (true) return new StrategyFail();}
      break;
    case 44:
      jj_consume_token(44);
      {if (true) return new StrategyMeta();}
      break;
    case 45:
      jj_consume_token(45);
      subterms = RuleNames();
      jj_consume_token(24);
      {if (true) return new StrategyOneRule(subterms);}
      break;
    case 46:
      jj_consume_token(46);
      subterms = RuleNames();
      jj_consume_token(24);
      {if (true) return new StrategyDcRule(subterms);}
      break;
    case 47:
      jj_consume_token(47);
      subterms = RuleNames();
      jj_consume_token(24);
      {if (true) return new StrategyDkRule(subterms);}
      break;
    case 48:
      jj_consume_token(48);
      subterms = StrategyTerms();
      jj_consume_token(24);
      {if (true) return new StrategyOneStrat(subterms);}
      break;
    case 49:
      jj_consume_token(49);
      subterms = StrategyTerms();
      jj_consume_token(24);
      {if (true) return new StrategyDcStrat(subterms);}
      break;
    case 50:
      jj_consume_token(50);
      subterms = StrategyTerms();
      jj_consume_token(24);
      {if (true) return new StrategyDkStrat(subterms);}
      break;
    case 51:
      jj_consume_token(51);
      stratBody = StrategyBody();
      jj_consume_token(24);
      subterms = new Vector(1);
      subterms.addElement(stratBody);
      {if (true) return new StrategyRepeat(subterms);}
      break;
    case 52:
      jj_consume_token(52);
      stratBody = StrategyBody();
      jj_consume_token(24);
      subterms = new Vector(1);
      subterms.addElement(stratBody);
      {if (true) return new StrategyIterate(subterms);}
      break;
    case 53:
      jj_consume_token(53);
      stratName = StrategyName();
      jj_consume_token(24);
      {if (true) return new StrategyCall(stratName);}
      break;
    case 54:
      jj_consume_token(54);
      subterms = RuleNames();
      jj_consume_token(24);
      {if (true) return new StrategyNormInRule(subterms);}
      break;
    case 55:
      jj_consume_token(55);
      subterms = RuleNames();
      jj_consume_token(24);
      {if (true) return new StrategyNormOutRule(subterms);}
      break;
    case 56:
      jj_consume_token(56);
      stratBody = StrategyBody();
      jj_consume_token(24);
      subterms = new Vector(1);
      subterms.addElement(stratBody);
      {if (true) return new StrategyTraversalAll(subterms);}
      break;
    case 57:
      jj_consume_token(57);
      stratBody = StrategyBody();
      jj_consume_token(24);
      subterms = new Vector(1);
      subterms.addElement(stratBody);
      {if (true) return new StrategyTraversalOne(subterms);}
      break;
    case 58:
      jj_consume_token(58);
      stratBody = StrategyBody();
      jj_consume_token(24);
      subterms = new Vector(1);
      subterms.addElement(stratBody);
      {if (true) return new StrategyTraversalSome(subterms);}
      break;
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public Lexem StrategyName() throws ParseException {
  Lexem name;
  int id;
    id = readInt();
    name = LexemStrategyName.get(id);
    if(name == null) {
      {if (true) throw new InternalError("strategyName sym" + id + " not found");}
    }
    {if (true) return name;}
    throw new Error("Missing return statement in function");
  }

  static final public StrategyTerm RuleName() throws ParseException {
  Lexem name;
  int id;
    id = readInt();
    name = LexemRuleName.get(id);
    if(name == null) {
      {if (true) throw new InternalError("ruleName sym" + id + " not found");}
    }
    {if (true) return new StrategyRuleName(name);}
    throw new Error("Missing return statement in function");
  }

  static final public Vector RuleNames() throws ParseException {
  Vector subterms = new Vector(3);
  StrategyTerm t;
    t = RuleName();
    subterms.addElement(t);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DOT:
      jj_consume_token(DOT);
      label_17:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INTEGER:
        case 20:
          ;
          break;
        default:
          jj_la1[35] = jj_gen;
          break label_17;
        }
        t = RuleName();
        jj_consume_token(DOT);
      subterms.addElement(t);
      }
      jj_consume_token(NIL);
      break;
    default:
      jj_la1[36] = jj_gen;
      ;
    }
      {if (true) return subterms;}
    throw new Error("Missing return statement in function");
  }

  static final public Vector StrategyTerms() throws ParseException {
  Vector subterms = new Vector(3);
  StrategyTerm t;
    t = StrategyBody();
    subterms.addElement(t);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      label_18:
      while (true) {
        jj_consume_token(COMMA);
        t = StrategyBody();
        subterms.addElement(t);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[37] = jj_gen;
          break label_18;
        }
      }
      break;
    default:
      jj_la1[38] = jj_gen;
      ;
    }
      {if (true) return subterms;}
    throw new Error("Missing return statement in function");
  }

  static final public Query QueryDeclaration() throws ParseException {
  int intSourceSort;
  int intResultSort;
  Term startWith;
  Term checkWith;
  int stratNameIndex;
  Lexem strategyName=null;
  int id;
    jj_consume_token(59);
    intSourceSort = readInt();
    jj_consume_token(COMMA);
    intResultSort = readInt();
    jj_consume_token(COMMA);
    stratNameIndex = readInt();
    jj_consume_token(COMMA);
    startWith = ElanTerm();
    jj_consume_token(COMMA);
    checkWith = ElanTerm();
    jj_consume_token(24);
    if( stratNameIndex != -1 ) {
      strategyName = LexemStrategyName.get(stratNameIndex);
    }
    {if (true) return new Query(intSourceSort,strategyName,startWith);}
    throw new Error("Missing return statement in function");
  }

  static final private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_1();
    jj_save(0, xla);
    return retval;
  }

  static final private boolean jj_3R_36() {
    if (jj_scan_token(35)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_1() {
    if (jj_3R_19()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_scan_token(DOT)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_25() {
    if (jj_scan_token(39)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_1()) { jj_scanpos = xsp; break; }
      if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    }
    if (jj_scan_token(NIL)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_24() {
    if (jj_scan_token(36)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_27()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_35() {
    if (jj_scan_token(34)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_34() {
    if (jj_scan_token(33)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_23() {
    if (jj_3R_26()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_33() {
    if (jj_scan_token(32)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_22() {
    if (jj_3R_25()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_29() {
    if (jj_scan_token(38)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_27()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_27() {
    if (jj_3R_30()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_32() {
    if (jj_scan_token(31)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_21() {
    if (jj_3R_24()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_20() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_21()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_19() {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_20()) { jj_scanpos = xsp; break; }
      if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    }
    if (jj_scan_token(NIL)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_26() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_28() {
    if (jj_scan_token(37)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_27()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_30() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_31() {
    if (jj_scan_token(30)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static private boolean jj_initialized_once = false;
  static public REFParserTokenManager token_source;
  static ASCII_CharStream jj_input_stream;
  static public Token token, jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static public boolean lookingAhead = false;
  static private boolean jj_semLA;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[39];
  static final private int[] jj_la1_0 = {0x100000,0x90000,0x90000,0x90000,0x90000,0x90000,0x90000,0x90000,0x90000,0x90000,0x90000,0x10000,0x100080,0x100080,0x100080,0x100080,0x100080,0x400000,0x100080,0x50000,0x1e800000,0x100080,0x1e800000,0x20000000,0x50000,0xc0000000,0x100080,0xc0000000,0x0,0x0,0x0,0x0,0x50000,0x0,0x0,0x100080,0x40000,0x80000,0x80000,};
  static final private int[] jj_la1_1 = {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xf,0x0,0xf,0xf0,0xf0,0x60,0x100,0x0,0x200,0x7fffc00,0x0,0x0,0x0,0x0,};
  static final private JJCalls[] jj_2_rtns = new JJCalls[1];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  public REFParser(java.io.InputStream stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new ASCII_CharStream(stream, 1, 1);
    token_source = new REFParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static public void ReInit(java.io.InputStream stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public REFParser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new ASCII_CharStream(stream, 1, 1);
    token_source = new REFParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public REFParser(REFParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(REFParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static final private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    return (jj_scanpos.kind != kind);
  }

  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  static final public Token getToken(int index) {
    Token t = lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.Vector jj_expentries = new java.util.Vector();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Enumeration enum = jj_expentries.elements(); enum.hasMoreElements();) {
        int[] oldentry = (int[])(enum.nextElement());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.addElement(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  static final public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[60];
    for (int i = 0; i < 60; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 39; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 60; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  static final public void enable_tracing() {
  }

  static final public void disable_tracing() {
  }

  static final private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 1; i++) {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
          }
        }
        p = p.next;
      } while (p != null);
    }
    jj_rescan = false;
  }

  static final private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
