#! /bin/csh
#        LGI             SPC        INP        OUT

if ($1 =~ *I*) then
echo "Interpreter"
itest    ans_completion  KNZ86      sat        iKNZ86
itest    ans_completion  Zeh89      sat        iZeh89
if ($1 =~ *L*) then
itest    ans_completion  curry      sat        icurry
itest    ans_completion  exa79      sat        iexa79
itest    ans_completion  exa80      sat        iexa80
#itest    ans_completion  exa85      sat        iexa85
#itest    ans_completion  expf       sat        iexpf
#itest    ans_completion  expoclos   sat        iexpoclos
itest    ans_completion  furtin     sat        ifurtin
itest    ans_completion  gdiv       sat        igdiv
itest    ans_completion  group      sat        igroup
#itest    ans_completion  p2         sat        ip2
itest    ans_completion  sample     sat        isample
itest    ans_completion  taussky    sat        itaussky
endif
endif

if ($1 =~ *J*) then
echo "Java Compiler"
jtest    ans  KNZ86              jKNZ86
jtest    ans  Zeh89              jZeh89
jtest    ans  curry              jcurry
jtest    ans  exa79              jexa79
jtest    ans  exa80              jexa80
jtest    ans  exa85              jexa85
jtest    ans  expf               jexpf
jtest    ans  expoclos           jexpoclos
jtest    ans  furtin             jfurtin
jtest    ans  gdiv               jgdiv
jtest    ans  group              jgroup
jtest    ans  p2                 jp2
jtest    ans  p8                 jp8
jtest    ans  sample             jsample
jtest    ans  taussky            jtaussky
endif


if ($1 =~ *I* && $1 =~ *A*) then
echo "Aterm-Interpreted"
aitest    ans_completion  KNZ86      sat        iKNZ86
aitest    ans_completion  Zeh89      sat        iZeh89
if ($1 =~ *L*) then
aitest    ans_completion  curry      sat        icurry
aitest    ans_completion  exa79      sat        iexa79
aitest    ans_completion  exa80      sat        iexa80
#aitest    ans_completion  exa85      sat        iexa85
#aitest    ans_completion  expf       sat        iexpf
#aitest    ans_completion  expoclos   sat        iexpoclos
aitest    ans_completion  furtin     sat        ifurtin
aitest    ans_completion  gdiv       sat        igdiv
aitest    ans_completion  group      sat        igroup
#aitest    ans_completion  p2         sat        ip2
aitest    ans_completion  sample     sat        isample
aitest    ans_completion  taussky    sat        itaussky
endif
endif

if ($1 =~ *C* && $1 !~ *A*) then
echo "Compiler"
#ctest    ans_completion  KNZ86      sat        cKNZ86
#ctest    ans_completion  Zeh89      sat        cZeh89
if ($1 =~ *L*) then
#ctest    ans_completion  curry      sat        ccurry
#ctest    ans_completion  exa79      sat        cexa79
#ctest    ans_completion  exa80      sat        cexa80
ctest    ans_completion  exa85      sat        cexa85
ctest    ans_completion  expf       sat        cexpf
ctest    ans_completion  expoclos   sat        cexpoclos
#ctest    ans_completion  furtin     sat        cfurtin
#ctest    ans_completion  gdiv       sat        cgdiv
#ctest    ans_completion  group      sat        cgroup
ctest    ans_completion  p2         sat        cp2
ctest    ans_completion  p5         sat        cp5
ctest    ans_completion  sample     sat        csample
ctest    ans_completion  taussky    sat        ctaussky
endif
endif

if ($1 =~ *C* && $1 =~ *A*) then
echo "Aterm-Compiler"
#actest    ans_completion  KNZ86      sat        cKNZ86
#actest    ans_completion  Zeh89      sat        cZeh89
if ($1 =~ *L*) then
#actest    ans_completion  curry      sat        ccurry
#actest    ans_completion  exa79      sat        cexa79
#actest    ans_completion  exa80      sat        cexa80
actest    ans_completion  exa85      sat        cexa85
actest    ans_completion  expf       sat        cexpf
actest    ans_completion  expoclos   sat        cexpoclos
#ctest    ans_completion  furtin     sat        cfurtin
#actest    ans_completion  gdiv       sat        cgdiv
#actest    ans_completion  group      sat        cgroup
actest    ans_completion  p2         sat        cp2
actest    ans_completion  p5         sat        cp5
actest    ans_completion  sample     sat        csample
actest    ans_completion  taussky    sat        ctaussky
endif
endif


