//! Runtime library of the programs generated by `elanc-rs`
//! (spec `docs/superpowers/specs/2026-10-10-s6-rust-compiler-design.md`,
//! decisions D2-D5).
//!
//! * [`term`]: shared terms [`H<T>`], one weak unique table per sort
//!   ([`impl_sort!`]), ids, statistics.
//! * [`release`]: iterative freeing of deep terms, across sorts.
//! * [`ac`]: canonical AC multisets and matching helpers.
//! * [`strat`]: continuations and strategy combinators.
//! * [`builtin`]: int (interpreter semantics), bool, string, stuck terms.
//! * [`print`]: the printer of the compiled C programs.
//! * [`driver`]: options, output, big-stack main thread, step counter.
//!
//! Standard library only; terms are per thread (`Rc`).

pub mod ac;
pub mod builtin;
pub mod driver;
pub mod print;
pub mod release;
pub mod strat;
pub mod term;

pub use ac::{AcSet, Rest};
pub use builtin::{Builtin, Int, Str};
pub use driver::{main_program, step, steps, Options, Session};
pub use print::{Print, Writer};
pub use strat::{DynStrat, Strat, K};
pub use term::{
    created_terms, fx_hash, live_terms, live_terms_of, purge, table_stats, Sort, Table, TableStats,
    H,
};
