//! Shared terms (spec D2, D5): every ELAN sort is a Rust `enum` generated by
//! `elanc-rs`, and a shared term of sort `T` is an [`H<T>`], a
//! reference-counted pointer to a node that is **hash-consed** in one weak
//! unique table per sort.
//!
//! * Equality of `H<T>` is pointer equality and its hash is the node's
//!   creation id, so the `PartialEq`/`Hash` derived on a generated enum are
//!   shallow (O(arity)): the table needs nothing else from a sort.
//! * Ids come from one counter per thread shared by all sorts. They order
//!   AC multisets (see [`crate::ac`]). A 64-bit counter never wraps.
//! * The table holds `Weak` pointers: a term nobody references is freed by
//!   reference counting; its slot is reused by a later insertion in the same
//!   probe chain or dropped when the table is rebuilt (purge).
//! * Freeing never touches the unique table, so a drop can happen anywhere
//!   (even while the table is borrowed by `intern`).
//! * Freeing is iterative (see [`crate::release`]), so dropping a deep term
//!   never overflows the stack, whatever the nesting of sorts.
//!
//! Everything is per thread (`Rc`, `thread_local!`): terms are `!Send`.

use std::cell::{Cell, RefCell};
use std::fmt;
use std::hash::{Hash, Hasher};
use std::mem::ManuallyDrop;
use std::ops::Deref;
use std::rc::{Rc, Weak};
use std::thread::LocalKey;

// ----------------------------------------------------------------------
// Sorts
// ----------------------------------------------------------------------

/// Implemented (generated) for every hash-consed sort enum, with
/// [`impl_sort!`](crate::impl_sort) or by hand with
/// [`unique_table!`](crate::unique_table).
///
/// The enum derives `PartialEq, Eq, Hash`: children are `H<_>` (pointer
/// equality, hash = id), builtins (`i64`, `bool`, [`Str`](crate::Str)),
/// [`AcSet`](crate::AcSet)s or unboxed `Copy` enums.
pub trait Sort: Eq + Hash + Sized + 'static {
    /// The unique table of this sort: one `thread_local!` per sort (Rust
    /// has no generic thread-locals, so each sort declares its own).
    fn table() -> &'static LocalKey<RefCell<Table<Self>>>;

    /// Hash of a node value, used by the unique table. The default hashes
    /// the derived `Hash`. A generated sort that looks terms up *by parts*
    /// before building them ([`H::find`]) overrides it with a hash it can
    /// also compute from the parts (e.g. [`crate::ac::ac_hash`] for an AC
    /// variant, [`fx_hash`] for the others); both must agree.
    #[inline]
    fn node_hash(&self) -> u64 {
        fx_hash(self)
    }
}

/// Body of `Sort::table` for a generated sort: one thread-local table.
/// It takes the type because a nested `static` cannot name `Self`.
#[macro_export]
macro_rules! unique_table {
    ($t:ty) => {
        fn table() -> &'static ::std::thread::LocalKey<::std::cell::RefCell<$crate::Table<$t>>> {
            ::std::thread_local! {
                static TABLE: ::std::cell::RefCell<$crate::Table<$t>> =
                    const { ::std::cell::RefCell::new($crate::Table::new()) };
            }
            &TABLE
        }
    };
}

/// `impl Sort for T` with the default hash: `impl_sort!(Prop);`.
#[macro_export]
macro_rules! impl_sort {
    ($t:ty) => {
        impl $crate::Sort for $t {
            $crate::unique_table!($t);
        }
    };
}

// ----------------------------------------------------------------------
// Hashing
// ----------------------------------------------------------------------

/// A fast multiplicative hasher (FxHash-like) for node values; children
/// contribute their 64-bit id.
#[derive(Clone, Copy)]
pub struct Fx(u64);

impl Default for Fx {
    fn default() -> Fx {
        Fx(0x9e37_79b9)
    }
}

impl Hasher for Fx {
    #[inline(always)]
    fn finish(&self) -> u64 {
        self.0 ^ (self.0 >> 29)
    }
    #[inline(always)]
    fn write(&mut self, b: &[u8]) {
        for &x in b {
            self.write_u64(x as u64)
        }
    }
    #[inline(always)]
    fn write_u8(&mut self, x: u8) {
        self.write_u64(x as u64)
    }
    #[inline(always)]
    fn write_u32(&mut self, x: u32) {
        self.write_u64(x as u64)
    }
    #[inline(always)]
    fn write_usize(&mut self, x: usize) {
        self.write_u64(x as u64)
    }
    #[inline(always)]
    fn write_u64(&mut self, x: u64) {
        self.0 = (self.0.rotate_left(5) ^ x).wrapping_mul(0x517c_c1b7_2722_0a95)
    }
}

/// [`Fx`] hash of a value (the default [`Sort::node_hash`]).
#[inline]
pub fn fx_hash<V: Hash + ?Sized>(v: &V) -> u64 {
    let mut h = Fx::default();
    v.hash(&mut h);
    h.finish()
}

// ----------------------------------------------------------------------
// Nodes, ids and counters
// ----------------------------------------------------------------------

pub(crate) struct Node<T> {
    id: u64,
    pub(crate) v: T,
}

impl<T> Drop for Node<T> {
    #[inline]
    fn drop(&mut self) {
        // const thread-local without destructor: always accessible
        LIVE.with(|c| c.set(c.get() - 1));
    }
}

thread_local! {
    static NEXT_ID: Cell<u64> = const { Cell::new(0) };
    static LIVE: Cell<u64> = const { Cell::new(0) };
}

/// Number of shared terms (all sorts) created on this thread so far; it is
/// also the id the next term will get.
pub fn created_terms() -> u64 {
    NEXT_ID.with(|c| c.get())
}

/// Number of shared terms (all sorts) alive on this thread.
pub fn live_terms() -> u64 {
    LIVE.with(|c| c.get())
}

// ----------------------------------------------------------------------
// H<T>: a shared term
// ----------------------------------------------------------------------

/// A shared (hash-consed) term of sort `T`. Two `H<T>` are equal iff they
/// are the same node; `Ord` is the creation-id order.
pub struct H<T: Sort>(ManuallyDrop<Rc<Node<T>>>);

impl<T: Sort> H<T> {
    /// The unique term with this top constructor and these (shared)
    /// children: an existing node if one is alive, else a new node.
    #[inline]
    pub fn new(v: T) -> H<T> {
        let h = v.node_hash();
        H(ManuallyDrop::new(
            T::table().with(|t| t.borrow_mut().intern(v, h)),
        ))
    }

    /// Look a term up by parts, without building its value: `hash` must be
    /// the [`Sort::node_hash`] the value would have, and `eq` tells whether
    /// a node value is the one wanted. Hook for "lookup before build" (spec
    /// risks: AC speed), e.g. an AC merge whose result already exists.
    #[inline]
    pub fn find(hash: u64, eq: impl FnMut(&T) -> bool) -> Option<H<T>> {
        T::table()
            .with(|t| t.borrow().find(hash, eq))
            .map(|rc| H(ManuallyDrop::new(rc)))
    }

    /// The node's creation id (hash of the term, order of AC multisets).
    #[inline(always)]
    pub fn id(&self) -> u64 {
        self.0.id
    }

    /// Number of `H` handles on this node (diagnostics, tests).
    pub fn ref_count(this: &Self) -> usize {
        Rc::strong_count(&this.0)
    }
}

impl<T: Sort> Drop for H<T> {
    /// Last reference: the node is freed by [`crate::release`], which never
    /// recurses (the children of a node being freed are queued).
    #[inline]
    fn drop(&mut self) {
        // SAFETY: self.0 is not used after this.
        let rc = unsafe { ManuallyDrop::take(&mut self.0) };
        if Rc::strong_count(&rc) != 1 {
            drop(rc); // just a decrement
        } else {
            crate::release::release(rc);
        }
    }
}

impl<T: Sort> Clone for H<T> {
    #[inline(always)]
    fn clone(&self) -> Self {
        H(ManuallyDrop::new(Rc::clone(&self.0)))
    }
}
impl<T: Sort> PartialEq for H<T> {
    #[inline(always)]
    fn eq(&self, o: &Self) -> bool {
        Rc::ptr_eq(&self.0, &o.0)
    }
}
impl<T: Sort> Eq for H<T> {}
impl<T: Sort> Hash for H<T> {
    #[inline(always)]
    fn hash<S: Hasher>(&self, s: &mut S) {
        s.write_u64(self.0.id)
    }
}
impl<T: Sort> PartialOrd for H<T> {
    #[inline(always)]
    fn partial_cmp(&self, o: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(o))
    }
}
/// Total order on shared terms of a sort: creation id (AC multisets).
impl<T: Sort> Ord for H<T> {
    #[inline(always)]
    fn cmp(&self, o: &Self) -> std::cmp::Ordering {
        self.0.id.cmp(&o.0.id)
    }
}
impl<T: Sort> Deref for H<T> {
    type Target = T;
    #[inline(always)]
    fn deref(&self) -> &T {
        &self.0.v
    }
}
impl<T: Sort + fmt::Display> fmt::Display for H<T> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        self.0.v.fmt(f)
    }
}
impl<T: Sort + fmt::Debug> fmt::Debug for H<T> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "#{}:{:?}", self.0.id, self.0.v)
    }
}

// ----------------------------------------------------------------------
// Unique table: open addressing, linear probing, Weak entries.
// ----------------------------------------------------------------------

struct Slot<T> {
    hash: u64,
    w: Option<Weak<Node<T>>>,
}

/// The weak unique table of a sort.
///
/// A slot is `(hash, Option<Weak>)`; a lookup compares the stored hash
/// first and touches the node only on a hash match. A dead entry (term
/// freed) is reused by the next insertion in its probe chain. When the used
/// slots (live or dead) exceed half the capacity the table is rebuilt: live
/// entries are reinserted and dead `Weak`s dropped (which deallocates the
/// freed nodes' boxes); the new capacity is the smallest power of two
/// >= [`MIN_CAPACITY`] holding the live entries at load <= 1/4, so the table
/// shrinks as well as grows. Its size is thus bounded by 4x the peak number
/// of live terms of the sort (or `MIN_CAPACITY`).
pub struct Table<T> {
    slots: Vec<Slot<T>>,
    used: usize,
}

/// Smallest capacity of a non-empty unique table.
pub const MIN_CAPACITY: usize = 1 << 12;

/// Sizes of a unique table (tests, statistics).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct TableStats {
    /// Number of slots.
    pub capacity: usize,
    /// Non-empty slots (live or dead entries).
    pub used: usize,
    /// Entries whose term is alive.
    pub live: usize,
}

impl<T: Sort> Table<T> {
    pub const fn new() -> Table<T> {
        Table {
            slots: Vec::new(),
            used: 0,
        }
    }

    fn intern(&mut self, v: T, h: u64) -> Rc<Node<T>> {
        if (self.used + 1) * 2 > self.slots.len() {
            self.rebuild();
        }
        let mask = self.slots.len() - 1;
        let mut i = h as usize & mask;
        let mut free = usize::MAX;
        loop {
            let s = &self.slots[i];
            match &s.w {
                None => break,
                Some(w) => {
                    if s.hash == h {
                        if let Some(rc) = w.upgrade() {
                            if rc.v == v {
                                return rc; // `v` is dropped here (no table access)
                            }
                        } else if free == usize::MAX {
                            free = i;
                        }
                    } else if free == usize::MAX && w.strong_count() == 0 {
                        free = i;
                    }
                }
            }
            i = (i + 1) & mask;
        }
        let id = NEXT_ID.with(|c| {
            let id = c.get();
            c.set(id + 1);
            id
        });
        LIVE.with(|c| c.set(c.get() + 1));
        let rc = Rc::new(Node { id, v });
        if free == usize::MAX {
            free = i;
            self.used += 1;
        }
        // Replacing a dead Weak deallocates its box.
        self.slots[free] = Slot {
            hash: h,
            w: Some(Rc::downgrade(&rc)),
        };
        rc
    }

    fn find(&self, h: u64, mut eq: impl FnMut(&T) -> bool) -> Option<Rc<Node<T>>> {
        if self.slots.is_empty() {
            return None;
        }
        let mask = self.slots.len() - 1;
        let mut i = h as usize & mask;
        while let Some(w) = &self.slots[i].w {
            if self.slots[i].hash == h {
                if let Some(rc) = w.upgrade() {
                    if eq(&rc.v) {
                        return Some(rc);
                    }
                }
            }
            i = (i + 1) & mask;
        }
        None
    }

    #[cold]
    fn rebuild(&mut self) {
        let live = self.live();
        let mut cap = MIN_CAPACITY;
        while cap < live * 4 {
            cap *= 2;
        }
        let old = std::mem::replace(
            &mut self.slots,
            (0..cap).map(|_| Slot { hash: 0, w: None }).collect(),
        );
        self.used = 0;
        let mask = cap - 1;
        for s in old {
            if let Some(w) = s.w {
                if w.strong_count() > 0 {
                    let mut i = s.hash as usize & mask;
                    while self.slots[i].w.is_some() {
                        i = (i + 1) & mask;
                    }
                    self.slots[i] = Slot {
                        hash: s.hash,
                        w: Some(w),
                    };
                    self.used += 1;
                }
                // a dead Weak is dropped here: its box is deallocated
            }
        }
    }

    /// Number of entries whose term is alive (O(capacity)).
    pub fn live(&self) -> usize {
        self.slots
            .iter()
            .filter(|s| s.w.as_ref().map_or(false, |w| w.strong_count() > 0))
            .count()
    }

    pub fn stats(&self) -> TableStats {
        TableStats {
            capacity: self.slots.len(),
            used: self.used,
            live: self.live(),
        }
    }
}

/// Number of live terms of sort `T` (O(table capacity)).
pub fn live_terms_of<T: Sort>() -> usize {
    T::table().with(|t| t.borrow().live())
}

/// Sizes of the unique table of sort `T`.
pub fn table_stats<T: Sort>() -> TableStats {
    T::table().with(|t| t.borrow().stats())
}

/// Purge the unique table of sort `T` now: drop its dead entries
/// (deallocating the boxes of freed nodes) and resize it to its live
/// entries. Tables also purge themselves when they fill up.
pub fn purge<T: Sort>() {
    T::table().with(|t| {
        let mut t = t.borrow_mut();
        if t.live() == 0 {
            *t = Table::new();
        } else {
            t.rebuild();
        }
    })
}
