all :
	cp choice1.* ../
	cp dcfail.* ../
	cp enum.* ../
	cp enum2.*  ../
	cp ident1.* ../
	cp match1.* ../
	cp match2.* ../
	cp match3.* ../
	cp match4.* ../
	cp match5.* ../
	cp queens4.* ../
	cp rep.* ../
	cp switch1.* ../
	cp switch2.* ../
	cp wpattern.* ../
