#! /bin/csh
#        LGI         SPC           INP        OUT

if ($1 =~ *I*) then
echo "Interpreter"
itest    clp         fibCLP        ex1       ex1
itest    clp         arithmeticCLP ex2       ex2
endif

