#		(c)	INRIA-Lorraine & CRIN
#			615, rue du Jardin Botanique, BP 101
#		        54602 Villers-les-Nancy
#			France
#			email: elan@loria.fr
#
#	$Source: /users/protheo/pot/ELAN/CVSELAN/elan/sources/Compiler/RuntimeSupport/ACMatcher/Makefile.common,v $
#	$Revision: 1.2 $
#	$Date: 1998/11/25 08:33:18 $
#	$Author: moreau $

# import CC
# import FAST
# import ARCH
# import ARCHFLAG
# import SPECIAL_FLAG
# import ELANLIB

MAKEINSTALLDIRS =
MAKEDISTDIRS    = $(ELANDIST)/Compiler/RuntimeSupport/ACMatcher


SRC    = Makefile.common\
      acmatchdefs.h   defs.h          free_types.h    solve_free.c    term_types.h\
      build_free.c    eker_tools.c    functions.h     solve_pure.c\
      build_match.c   eker_tools.h    gccmatch.c      state_types.h\
      build_pure.c    flatten.c       pure_types.h    sym_types.h\

all: 

makefile:

install:

dist: dist-dirs 
	cp $(SRC) $(ELANDIST)/Compiler/RuntimeSupport/ACMatcher

clean :
	rm -f core a.out main *.o *~ y.tab.[ch] y.output lex.yy.c $(ARCH)/*.o $(ARCH)/*.a

