/* Generated By:JavaCC: Do not edit this line. REFParserTokenManager.java */
package rem.parser;
import java.util.*;
import rem.compiler.*;
import rem.exception.*;

public class REFParserTokenManager implements REFParserConstants
{
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 41:
         return jjStopAtPos(0, 24);
      case 44:
         return jjStopAtPos(0, 19);
      case 45:
         return jjStopAtPos(0, 20);
      case 46:
         return jjStopAtPos(0, 18);
      case 58:
         return jjStopAtPos(0, 21);
      case 59:
         return jjStopAtPos(0, 41);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x4000000L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x6000000000000L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x100008000L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x40000000L);
      case 71:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x1600800400L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x100000001000L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      case 79:
         return jjMoveStringLiteralDfa1_0(0x1000000000000L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x4000000000L);
      case 81:
         return jjMoveStringLiteralDfa1_0(0x100000000000000L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x20002000L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x10800004800L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x8002000000L);
      case 86:
         return jjMoveStringLiteralDfa1_0(0x80000000L);
      case 87:
         return jjMoveStringLiteralDfa1_0(0x2000000000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x20000000000000L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0xc00000000000L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x10000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x80000000000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x10040000000000L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0xc0000000020000L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x200000000000L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x8000000000000L);
      default :
         return jjMoveNfa_0(1, 0);
   }
}
static private final int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000L);
      case 67:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000000L);
      case 68:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000000L);
      case 70:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000L);
      case 72:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000L);
      case 75:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000000L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000200000000L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000L);
      case 83:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L);
      case 84:
         return jjMoveStringLiteralDfa2_0(active0, 0x10800000000L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000020000000L);
      case 86:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000L);
      case 87:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x20080000000000L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000000L);
      case 100:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(1, 42);
         return jjMoveStringLiteralDfa2_0(active0, 0x800400L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000000L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000L);
      case 107:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000018000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0xc0000000001800L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000004000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x8002000L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private final int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 40:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStopAtPos(2, 46);
         else if ((active0 & 0x800000000000L) != 0L)
            return jjStopAtPos(2, 47);
         else if ((active0 & 0x2000000000000L) != 0L)
            return jjStopAtPos(2, 49);
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStopAtPos(2, 50);
         break;
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L);
      case 69:
         return jjMoveStringLiteralDfa3_0(active0, 0x101002400000000L);
      case 70:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000L);
      case 72:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000L);
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L);
      case 82:
         return jjMoveStringLiteralDfa3_0(active0, 0x10880000000L);
      case 84:
         return jjMoveStringLiteralDfa3_0(active0, 0x100200000000L);
      case 89:
         return jjMoveStringLiteralDfa3_0(active0, 0x8040000000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x14400000L);
      case 100:
         if ((active0 & 0x10000L) != 0L)
            return jjStopAtPos(2, 16);
         return jjMoveStringLiteralDfa3_0(active0, 0x9000L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x10200000800400L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000000L);
      case 108:
         if ((active0 & 0x20000L) != 0L)
            return jjStopAtPos(2, 17);
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000002000L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000002000000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0xc0000000004800L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private final int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 40:
         if ((active0 & 0x8000000L) != 0L)
            return jjStopAtPos(3, 27);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStopAtPos(3, 31);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStopAtPos(3, 33);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStopAtPos(3, 36);
         else if ((active0 & 0x8000000000L) != 0L)
            return jjStopAtPos(3, 39);
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStopAtPos(3, 45);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStopAtPos(3, 48);
         break;
      case 65:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStopAtPos(3, 44);
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000L);
      case 68:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 69:
         return jjMoveStringLiteralDfa4_0(active0, 0x4020000000L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000L);
      case 77:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000L);
      case 78:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000L);
      case 82:
         return jjMoveStringLiteralDfa4_0(active0, 0x100002100000000L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000002002000L);
      case 108:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStopAtPos(3, 43);
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000000L);
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0xc0000000400000L);
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x10800400L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000004000000L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x800L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private final int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 40:
         if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(4, 25);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStopAtPos(4, 26);
         else if ((active0 & 0x20000000L) != 0L)
            return jjStopAtPos(4, 29);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(4, 30);
         else if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(4, 32);
         else if ((active0 & 0x20000000000000L) != 0L)
            return jjStopAtPos(4, 53);
         break;
      case 69:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000L);
      case 78:
         return jjMoveStringLiteralDfa5_0(active0, 0x800002000L);
      case 82:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000L);
      case 84:
         return jjMoveStringLiteralDfa5_0(active0, 0x10400000000L);
      case 89:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000000L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x18000000000000L);
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000000L);
      case 107:
         if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(4, 28);
         break;
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000L);
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000000000L);
      case 115:
         if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(4, 11);
         break;
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x804400L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private final int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 40:
         if ((active0 & 0x800000L) != 0L)
            return jjStopAtPos(5, 23);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStopAtPos(5, 34);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStopAtPos(5, 37);
         else if ((active0 & 0x100000000000000L) != 0L)
            return jjStopAtPos(5, 56);
         break;
      case 69:
         return jjMoveStringLiteralDfa6_0(active0, 0x14000000000L);
      case 71:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x402000L);
      case 101:
         return jjMoveStringLiteralDfa6_0(active0, 0x5000L);
      case 102:
         if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(5, 15);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x400L);
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000000000L);
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x18000000000000L);
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private final int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 40:
         if ((active0 & 0x800000000L) != 0L)
            return jjStopAtPos(6, 35);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStopAtPos(6, 38);
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStopAtPos(6, 54);
         break;
      case 42:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000000L);
      case 71:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000000L);
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000000000L);
      case 102:
         return jjMoveStringLiteralDfa7_0(active0, 0x400L);
      case 103:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000L);
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000L);
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000L);
      case 115:
         if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(6, 12);
         break;
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private final int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 40:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStopAtPos(7, 51);
         else if ((active0 & 0x80000000000000L) != 0L)
            return jjStopAtPos(7, 55);
         break;
      case 42:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000000000L);
      case 70:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000L);
      case 89:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000000L);
      case 101:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000L);
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x400L);
      case 121:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private final int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 40:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStopAtPos(8, 40);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStopAtPos(8, 52);
         break;
      case 78:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000L);
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0x400L);
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000L);
      case 115:
         if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(8, 13);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private final int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000L);
      case 114:
         return jjMoveStringLiteralDfa10_0(active0, 0x400400L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
static private final int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 83:
         return jjMoveStringLiteralDfa11_0(active0, 0x400000L);
      case 109:
         return jjMoveStringLiteralDfa11_0(active0, 0x4000L);
      case 115:
         if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(10, 10);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
static private final int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa12_0(active0, 0x4000L);
      case 111:
         return jjMoveStringLiteralDfa12_0(active0, 0x400000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
static private final int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 114:
         return jjMoveStringLiteralDfa13_0(active0, 0x400000L);
      case 115:
         if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(12, 14);
         break;
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
static private final int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 116:
         if ((active0 & 0x400000L) != 0L)
            return jjStopAtPos(13, 22);
         break;
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
static private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
static private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
static private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 31;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 7)
                        kind = 7;
                     jjCheckNAdd(0);
                  }
                  else if (curChar == 47)
                     jjAddStates(0, 1);
                  else if (curChar == 34)
                     jjCheckNAddStates(2, 4);
                  else if (curChar == 39)
                     jjAddStates(5, 6);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  jjCheckNAdd(0);
                  break;
               case 2:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     jjCheckNAdd(3);
                  break;
               case 3:
                  if (curChar == 39 && kind > 8)
                     kind = 8;
                  break;
               case 5:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAdd(3);
                  break;
               case 6:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(7, 3);
                  break;
               case 7:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(3);
                  break;
               case 8:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 9:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(7);
                  break;
               case 10:
                  if (curChar == 34)
                     jjCheckNAddStates(2, 4);
                  break;
               case 11:
                  if ((0xfffffffbffffdfffL & l) != 0L)
                     jjCheckNAddStates(2, 4);
                  break;
               case 13:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(2, 4);
                  break;
               case 14:
                  if (curChar == 34 && kind > 9)
                     kind = 9;
                  break;
               case 15:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(7, 10);
                  break;
               case 16:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(2, 4);
                  break;
               case 17:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 18:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(16);
                  break;
               case 19:
                  if (curChar == 47)
                     jjAddStates(0, 1);
                  break;
               case 20:
                  if (curChar == 47)
                     jjCheckNAddStates(11, 13);
                  break;
               case 21:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(11, 13);
                  break;
               case 22:
                  if ((0x2400L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 23:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 24:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(26, 27);
                  break;
               case 26:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(26, 27);
                  break;
               case 27:
                  if (curChar == 42)
                     jjCheckNAddStates(14, 16);
                  break;
               case 28:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(29, 27);
                  break;
               case 29:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(29, 27);
                  break;
               case 30:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAdd(3);
                  break;
               case 4:
                  if (curChar == 92)
                     jjAddStates(17, 19);
                  break;
               case 5:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAdd(3);
                  break;
               case 11:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(2, 4);
                  break;
               case 12:
                  if (curChar == 92)
                     jjAddStates(20, 22);
                  break;
               case 13:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(2, 4);
                  break;
               case 21:
                  jjAddStates(11, 13);
                  break;
               case 26:
                  jjCheckNAddTwoStates(26, 27);
                  break;
               case 28:
               case 29:
                  jjCheckNAddTwoStates(29, 27);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 11:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(2, 4);
                  break;
               case 21:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(11, 13);
                  break;
               case 26:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(26, 27);
                  break;
               case 28:
               case 29:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(29, 27);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 31 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   20, 25, 11, 12, 14, 2, 4, 11, 12, 16, 14, 21, 22, 24, 27, 28, 
   30, 5, 6, 8, 13, 15, 17, 
};
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, 
"\111\144\145\156\164\151\146\151\145\162\163", "\123\157\162\164\163", "\115\157\144\165\154\145\163", 
"\122\165\154\145\116\141\155\145\163", "\123\164\162\141\164\145\147\171\116\141\155\145\163", 
"\105\156\144\104\145\146", "\145\156\144", "\156\151\154", "\56", "\54", "\55", "\72", 
"\107\162\141\155\155\141\162\106\157\162\123\157\162\164", "\111\144\145\156\164\50", "\51", "\124\171\160\145\50", 
"\103\150\141\162\50", "\116\165\155\50", "\102\154\141\156\153", "\122\125\114\105\50", 
"\106\123\131\115\50", "\126\101\122\50", "\105\126\101\122\50", "\111\116\124\50", 
"\111\104\105\116\124\50", "\123\124\122\111\116\107\50", "\111\106\106\50", "\127\110\105\122\105\50", 
"\120\127\110\105\122\105\50", "\124\122\131\50", "\123\124\122\101\124\105\107\131\50", "\73", "\151\144", 
"\146\141\151\154", "\115\105\124\101", "\157\156\145\50", "\144\143\50", "\144\153\50", 
"\117\116\105\50", "\104\103\50", "\104\113\50", "\162\145\160\145\141\164\52\50", 
"\151\164\145\162\141\164\145\52\50", "\143\141\154\154\50", "\156\157\162\155\151\156\50", 
"\156\157\162\155\157\165\164\50", "\121\125\105\122\131\50", };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x1ffffffffffff81L, 
};
static final long[] jjtoSkip = {
   0x7eL, 
};
static private ASCII_CharStream input_stream;
static private final int[] jjrounds = new int[31];
static private final int[] jjstateSet = new int[62];
static protected char curChar;
public REFParserTokenManager(ASCII_CharStream stream)
{
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}
public REFParserTokenManager(ASCII_CharStream stream, int lexState)
{
   this(stream);
   SwitchTo(lexState);
}
static public void ReInit(ASCII_CharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 31; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
static public void ReInit(ASCII_CharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static private final Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

public static final Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
