package completion;

import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.util.*;

/* This frame contain all the rules generated by ELAN for the system. *
 * The rules are displayed in a JTable. The first and the third       *
 * column contain respectively the left part and the right part of    *
 * the rule.*/

public class CompletionFrame extends JFrame{

    private JTable table;
    private Container container;
    
    /* The argument is a vector of Rule, which is the java object    *
     * representing equalities or oriented rules.*/
    public CompletionFrame(Vector rules, String name){
	super("Completion for system : " + name);
	container = getContentPane();
	container.setLayout(new BorderLayout(5, 5));
	JPanel panel = new JPanel(new BorderLayout());
	panel.setBorder(BorderFactory.createLineBorder(Color.gray));
	
	MyTableModel tm = new MyTableModel(0, 3);
	Vector ve = new Vector(3);
	ve.add("");
	ve.add("");
	ve.add("");
	tm.setColumnIdentifiers(ve);
	table = new JTable(tm);
	table.setPreferredScrollableViewportSize(new Dimension(800, 200));
	TableColumn column;
	for(int i = 0; i < 3; i++){
	    column = table.getColumnModel().getColumn(i);
	    if(i == 1){
		column.setPreferredWidth(20);
	    } 
	    else{
		column.setPreferredWidth(360);
	    }
	}
	JScrollPane scrollPane = new JScrollPane(table);

	for(int i = 0; i < rules.size(); i++){
	    Rule rule = (Rule) rules.get(i);
	    Vector row = new Vector(3);
	    row.add(rule.getLeft());
	    row.add("->");
	    row.add(rule.getRight());
	    ((MyTableModel)table.getModel()).addRow(row);
	    table.setRowHeight(i, 20);
	}

	if(table.getRowCount() < 10)
	    table.setPreferredScrollableViewportSize(new Dimension(800, (1+table.getRowCount()) * table.getRowHeight()));
	else
	    table.setPreferredScrollableViewportSize(new Dimension(800, 200));

	JLabel label = new JLabel("Completion");
	panel.add(label, BorderLayout.NORTH);
	panel.add(scrollPane, BorderLayout.CENTER);
	container.add(panel);

	pack();
	setVisible(true);
    }
    
}
