package completion;

//import elan.completion.spcParser.*;
import completion.parser.*;

import java.io.*;
import java.util.*;
import java.lang.reflect.*;
import javax.swing.*;
import java.awt.*;
import javax.swing.table.*;


public class Specification{

    /* This class represents the system to be studied. */


    // features that describe the specification.


    /* The list of variables. This vector contains Strings  *
     * representations of variables. */
    private Vector variables;

    /* The list of operators. This vector contains Operators*
     * object which represents operators used in the system.*/
    private Vector operators;

    /* The system. It is a vector containing equations which*
     * compose the system. Each equation is represented by  *
     * the object Rule.*/
    private Vector system;

    /* This vector contains the result given by ELAN for the* 
     * orientation of the system. */
    private Vector orientedRules = null;

    /* The critical pairs of the system returned by ELAN. */
    private Vector criticalPairs = null;

    /* The completion of the system. */
    private Vector completion = null;

    
    
    /* This string contain all warning generating by parsing.*/
    private String warning;

    
    // Constructors
    public Specification(){
    }

    /* The file in argument is the kbc file containing the   *
     * textual representation of the system. This file is    *
     * parsed to create the specification. The parser is     *
     * generated by javacc, and is in the package            *
     * completion.parser the integer choice is just here to  *
     * transmit the context to the parser. Contexts are      *
     * either save or open.*/
    public Specification(File f, int choice) throws KbcException, Exception{
	Parser parser = new Parser(new FileInputStream(f));
	String error;
	if(!(error = parser.inputKbc(choice)).equals(""))
	    throw(new KbcException("error in source file. " + error));
	warning = parser.getWarning();
	variables = parser.getVariables();
	operators = parser.getOperators();
	system = parser.getRules();
	doSpcFile(f);
    }

    /* This method generate the spc file which will be used by*
     * ELAN. */
    private void doSpcFile(File f) throws Exception{
	String name = f.getPath();
	name = name.replaceFirst(".kbc", ".spc");
	File file = new File(name);
	createFile(file);
    }

    /* This method will write the right fields in the spc file.*/
    public void createFile(File f) throws Exception{
	FileWriter fw = new FileWriter(f);
	String name = f.getName();
	name = name.replaceFirst("\\.spc", "");
	fw.write("specification " + name + "\n\n");
	fw.write("Vars\n\t");
	for(int i = 0; i < variables.size(); i++)
	    fw.write((String) variables.get(i) + " ");
	fw.write("\n\nOps\n\t");
	for(int i = 0; i < operators.size(); i++)
	    writeOperator((Operator) operators.get(i), fw);
	fw.write("\n\nPrec\n\t");
	for(int i = 0; i < operators.size(); i++)
	    writePrec((Operator) operators.get(i), fw);
	fw.write("\n\nSystem\n");
	for(int i = 0; i < system.size(); i++)
	    writeSystem((Rule) system.get(i), fw);
	fw.write("\tnil\n\n\nend of specification\n\t");
	fw.close();
    }

    /* For writting operators. */
    public void writeOperator(Operator op, FileWriter fw) throws Exception{
	fw.write(op.getName() + ":" + op.getArity() + " ");
    }

    /* For writting precedance.*/
    public void writePrec(Operator op, FileWriter fw) throws Exception{
	fw.write(op.getName() + ":" + op.getPriority() + " ");
    }

    /* For writting system.*/
    public void writeSystem(Rule syst, FileWriter fw) throws Exception{
	fw.write("\t" + syst.getLeft().toString() + " = " + syst.getRight().toString() + "\n");
    }

    /* This method search the rules which are different of *
     * system's rules, and set them their flag. */
    private void checkChanges(){
	if(orientedRules != null){
	    for(int i = 0; i < orientedRules.size(); i++){
		Rule rule = (Rule) orientedRules.get(i);
		boolean found = false;
		for(int j = 0; j < system.size(); j++){
		    Rule equation = (Rule) system.get(j);
		    if(rule.equals(equation)){
			break;
		    }
		    else if(rule.isOpposit(equation)){
			//found = true; 
			rule.setFlag(true);
			break;
		    }
		}
	    }
	}
    }



    /* methods permitting to access the features */


    public Vector getSystem(){
	return system;
    }

    public Vector getOrientedRules(){
	return orientedRules;
    }

    public Vector getCriticalPairs(){
	return criticalPairs;
    }

    public Vector getCompletion(){
	return completion;
    }
    
    public String getWarning(){
	return warning;
    }
    

    /* For setting the fields */

    public void setOrientedRules(Vector rules){
	orientedRules = rules;
	checkChanges();
    }

    public void setCriticalPairs(Vector pairs){
	criticalPairs = pairs;
    }

     public void setCompletion(Vector rules){
	completion = rules;
    }
}
