elanlibdir = $(datadir)/elanlib
noquotedir  = $(elanlibdir)/noquote

ELANLIB_NOQUOTE = \
			applySubstOn.eln\
			atom.eln\
			atomP.eln\
			eqSystem.eln\
			hornClauseSyntax.eln\
			ident.eln\
			identifier.eln\
			sigSyntax.eln\
			substitution.eln\
			syntacticUnification.eln\
			termCommons.eln

EXTRA_DIST  = $(ELANLIB_NOQUOTE)
noquote_DATA = $(ELANLIB_NOQUOTE)

