/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package completion.parser;

public interface ParserConstants {

  int EOF = 0;
  int VIRG = 1;
  int UNDER = 2;
  int ARROW = 3;
  int PARO = 4;
  int PARF = 5;
  int EQ = 6;
  int DOT = 7;
  int SEMICOLON = 8;
  int INF = 9;
  int DP = 10;
  int PERCENT = 11;
  int RES = 12;
  int CP = 13;
  int ID = 14;
  int NIL = 15;
  int VAR = 16;
  int COMPOSE = 17;
  int PREC = 18;
  int VARS = 19;
  int SYST = 20;
  int NUMBER = 25;
  int DIGIT = 26;
  int IDF = 27;
  int LETTER = 28;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\",\"",
    "\"_\"",
    "\"->\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\".\"",
    "\";\"",
    "\"<\"",
    "\":\"",
    "\"%\"",
    "\"result\"",
    "\"CP\"",
    "\"identity\"",
    "\"nil\"",
    "\"var\"",
    "\"o\"",
    "\"prec\"",
    "\"vars\"",
    "\"syst\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NUMBER>",
    "<DIGIT>",
    "<IDF>",
    "<LETTER>",
  };

}
