noinst_LIBRARIES = libmatch.a

CFLAGS = -g -Wall -Wstrict-prototypes
CXXFLAGS = -g -Wall -Wstrict-prototypes

libmatch_a_SOURCES = build_free.c defs.h functions.h solve_free.c \
                     term_types.h build_match.c flatten.c minitools.h \
                     solve_pure.c tools.c build_pure.c free_types.h \
                     pure_types.h state_types.h tools.h gccmatch.c sym_types.h
