elanlibdir = $(datadir)/elanlib
strategydir  = $(elanlibdir)/strategy

ELANLIB_STRATEGY = \
			Any.eln\
			Meta_apply.eln\
			Meta_capply.eln\
			Meta_strat.eln\
			any.eln\
			booleg.eln\
			carray.eln\
			commit.eln\
			integ.eln\
			loops.eln\
			meta.eln\
			strapply.eln\
			strat.eln\
			strcapply.eln\
			strconc.eln\
			strsig.eln\
			symbol.eln\
			tcstrat.eln\
			tpstrat.eln

EXTRA_DIST  = $(ELANLIB_STRATEGY)
strategy_DATA = $(ELANLIB_STRATEGY)

