/* Generated By:JavaCC: Do not edit this line. REFParserConstants.java */
package rem.parser;

public interface REFParserConstants {

  int EOF = 0;
  int INTEGER = 7;
  int CHARACTER_LITERAL = 8;
  int STRING_LITERAL = 9;
  int LEXEM_DECLARATION = 10;
  int SORT_DECLARATION = 11;
  int MODULE_DECLARATION = 12;
  int RULENAME_DECLARATION = 13;
  int STRATEGYNAME_DECLARATION = 14;
  int ENDDEF = 15;
  int END = 16;
  int NIL = 17;
  int DOT = 18;
  int COMMA = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"Identifiers\"",
    "\"Sorts\"",
    "\"Modules\"",
    "\"RuleNames\"",
    "\"StrategyNames\"",
    "\"EndDef\"",
    "\"end\"",
    "\"nil\"",
    "\".\"",
    "\",\"",
    "\"-\"",
    "\":\"",
    "\"GrammarForSort\"",
    "\"Ident(\"",
    "\")\"",
    "\"Type(\"",
    "\"Char(\"",
    "\"Num(\"",
    "\"Blank\"",
    "\"RULE(\"",
    "\"FSYM(\"",
    "\"VAR(\"",
    "\"EVAR(\"",
    "\"INT(\"",
    "\"IDENT(\"",
    "\"STRING(\"",
    "\"IFF(\"",
    "\"WHERE(\"",
    "\"PWHERE(\"",
    "\"TRY(\"",
    "\"STRATEGY(\"",
    "\";\"",
    "\"id\"",
    "\"fail\"",
    "\"META\"",
    "\"one(\"",
    "\"dc(\"",
    "\"dk(\"",
    "\"ONE(\"",
    "\"DC(\"",
    "\"DK(\"",
    "\"repeat*(\"",
    "\"iterate*(\"",
    "\"call(\"",
    "\"normin(\"",
    "\"normout(\"",
    "\"tall(\"",
    "\"tone(\"",
    "\"tsome(\"",
    "\"rewrite(\"",
    "\"QUERY(\"",
  };

}
