ARCH := $(shell uname -m)
ifeq '$(ARCH)' "alpha"
CC = cc
#LIBELAN = -lelanmv -lexc
LIBELAN = -lelan
FAST = -fast
YLIB = -ll -ly
else
ifneq (,$(findstring 86,$(ARCH)))
CC = gcc -pipe
LIBELAN = -lCsetChoicePoint
FAST = -O3 -march=i686
YLIB = -lfl
else
CC = gcc -pipe
LIBELAN = -lCsetChoicePoint
FAST = -O2
YLIB = -ll -ly
endif
endif
INC = -I$(ELANLIB)/Compiler/ -I$(ELANLIB)/Compiler/$(ARCH)
BASIC_OPT = -DXHCODE -DHASHCODE -DBORO -DBGSHARE -DNONUNDERSCORED -DBITSETMASK -DGCMEM -DCOLOR
CC_OPT = -DCSETCHP -DBITSET32 $(BASIC_OPT) $(INC)
LIBCOQ=
LIB = $(LIBCOQ) -L$(ELANLIB)/Compiler/$(ARCH) $(LIBELAN) -lTermIO -lRuntimeSupport -lACMatcher -learley $(YLIB) -lgc



all: main

main.o: main.c main.h
	$(CC) $(FAST) $(CC_OPT) -c main.c

main: main.o
	$(CC) $(CC_OPT) -o main main.o -L. -lTest $(LIB)
