#! /bin/csh
#        LGI         SPC        INP        OUT

if ($1 =~ *I*) then
echo "Interpreter"
itest    matchingAC  ctesig     ex1       ex1
itest    matchingAC  ctesig     ex2       ex2
itest    matchingAC  ctesig     ex3       ex3
itest    matchingAC  ctesig     ex4       ex4
endif

